// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeacherScheduleApp.Data;

#nullable disable

namespace TeacherScheduleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817165318_AddImportBatchToEvents")]
    partial class AddImportBatchToEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TeacherScheduleApp.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AutoGeneratedForDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCollision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportLabel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LunchEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LunchStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentEventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoEventNameLunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoEventNamePostLunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoEventNamePreLunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FridayArrival")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FridayDeparture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FridayLunchEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FridayLunchStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalEndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalStartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxBreakDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinBreakDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MondayArrival")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MondayDeparture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MondayLunchEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MondayLunchStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThursdayArrival")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThursdayDeparture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThursdayLunchEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThursdayLunchStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TuesdayArrival")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TuesdayDeparture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TuesdayLunchEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TuesdayLunchStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WednesdayArrival")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WednesdayDeparture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WednesdayLunchEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WednesdayLunchStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("LunchEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("LunchStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.Event", b =>
                {
                    b.HasOne("TeacherScheduleApp.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("ParentEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
