using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TeacherScheduleApp.Migrations
{
    /// <inheritdoc />
    public partial class AddYearToGlobalSettings : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Events",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Title = table.Column<string>(type: "TEXT", nullable: false),
                    StartTime = table.Column<string>(type: "TEXT", nullable: false),
                    EndTime = table.Column<string>(type: "TEXT", nullable: false),
                    AllDay = table.Column<bool>(type: "INTEGER", nullable: false),
                    Description = table.Column<string>(type: "TEXT", nullable: true),
                    IsDeleted = table.Column<bool>(type: "INTEGER", nullable: false),
                    EventType = table.Column<int>(type: "INTEGER", nullable: false),
                    ArrivalTime = table.Column<DateTime>(type: "TEXT", nullable: false),
                    DepartureTime = table.Column<DateTime>(type: "TEXT", nullable: false),
                    LunchStart = table.Column<DateTime>(type: "TEXT", nullable: false),
                    LunchEnd = table.Column<DateTime>(type: "TEXT", nullable: false),
                    IsAutoGenerated = table.Column<bool>(type: "INTEGER", nullable: false),
                    HasCollision = table.Column<bool>(type: "INTEGER", nullable: false),
                    AutoGeneratedForDate = table.Column<DateTime>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Events", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "GlobalSettings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Year = table.Column<int>(type: "INTEGER", nullable: false),
                    GlobalStartTime = table.Column<string>(type: "TEXT", nullable: false),
                    GlobalEndTime = table.Column<string>(type: "TEXT", nullable: false),
                    EmployeeName = table.Column<string>(type: "TEXT", nullable: false),
                    Department = table.Column<string>(type: "TEXT", nullable: false),
                    MondayArrival = table.Column<string>(type: "TEXT", nullable: false),
                    MondayDeparture = table.Column<string>(type: "TEXT", nullable: false),
                    MondayLunchStart = table.Column<string>(type: "TEXT", nullable: false),
                    MondayLunchEnd = table.Column<string>(type: "TEXT", nullable: false),
                    TuesdayArrival = table.Column<string>(type: "TEXT", nullable: false),
                    TuesdayDeparture = table.Column<string>(type: "TEXT", nullable: false),
                    TuesdayLunchStart = table.Column<string>(type: "TEXT", nullable: false),
                    TuesdayLunchEnd = table.Column<string>(type: "TEXT", nullable: false),
                    WednesdayArrival = table.Column<string>(type: "TEXT", nullable: false),
                    WednesdayDeparture = table.Column<string>(type: "TEXT", nullable: false),
                    WednesdayLunchStart = table.Column<string>(type: "TEXT", nullable: false),
                    WednesdayLunchEnd = table.Column<string>(type: "TEXT", nullable: false),
                    ThursdayArrival = table.Column<string>(type: "TEXT", nullable: false),
                    ThursdayDeparture = table.Column<string>(type: "TEXT", nullable: false),
                    ThursdayLunchStart = table.Column<string>(type: "TEXT", nullable: false),
                    ThursdayLunchEnd = table.Column<string>(type: "TEXT", nullable: false),
                    FridayArrival = table.Column<string>(type: "TEXT", nullable: false),
                    FridayDeparture = table.Column<string>(type: "TEXT", nullable: false),
                    FridayLunchStart = table.Column<string>(type: "TEXT", nullable: false),
                    FridayLunchEnd = table.Column<string>(type: "TEXT", nullable: false),
                    MinBreakDuration = table.Column<string>(type: "TEXT", nullable: false),
                    MaxBreakDuration = table.Column<string>(type: "TEXT", nullable: false),
                    AutoEventNamePreLunch = table.Column<string>(type: "TEXT", nullable: false),
                    AutoEventNameLunch = table.Column<string>(type: "TEXT", nullable: false),
                    AutoEventNamePostLunch = table.Column<string>(type: "TEXT", nullable: false),
                    Semester = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GlobalSettings", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UserSettings",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Date = table.Column<DateTime>(type: "TEXT", nullable: false),
                    ArrivalTime = table.Column<TimeSpan>(type: "TEXT", nullable: false),
                    DepartureTime = table.Column<TimeSpan>(type: "TEXT", nullable: false),
                    LunchStart = table.Column<TimeSpan>(type: "TEXT", nullable: false),
                    LunchEnd = table.Column<TimeSpan>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserSettings", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Events");

            migrationBuilder.DropTable(
                name: "GlobalSettings");

            migrationBuilder.DropTable(
                name: "UserSettings");
        }
    }
}
