using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TeacherScheduleApp.Migrations
{
    /// <inheritdoc />
    public partial class OptimizeQueriesAndIndexes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Events_AutoGeneratedForDate",
                table: "Events");

            migrationBuilder.DropIndex(
                name: "IX_Events_EmployeeId",
                table: "Events");

            migrationBuilder.DropIndex(
                name: "IX_Events_StartTime",
                table: "Events");

            migrationBuilder.CreateIndex(
                name: "IX_Events_EmployeeId_IsAutoGenerated_AutoGeneratedForDate",
                table: "Events",
                columns: new[] { "EmployeeId", "IsAutoGenerated", "AutoGeneratedForDate" });

            migrationBuilder.CreateIndex(
                name: "IX_Events_EmployeeId_IsDeleted_EndTime",
                table: "Events",
                columns: new[] { "EmployeeId", "IsDeleted", "EndTime" });

            migrationBuilder.CreateIndex(
                name: "IX_Events_EmployeeId_IsDeleted_ImportBatchId",
                table: "Events",
                columns: new[] { "EmployeeId", "IsDeleted", "ImportBatchId" });

            migrationBuilder.CreateIndex(
                name: "IX_Events_EmployeeId_IsDeleted_StartTime",
                table: "Events",
                columns: new[] { "EmployeeId", "IsDeleted", "StartTime" });

            migrationBuilder.CreateIndex(
                name: "IX_Events_EmployeeId_ParentEventId",
                table: "Events",
                columns: new[] { "EmployeeId", "ParentEventId" });

            migrationBuilder.CreateIndex(
                name: "IX_DaySettings_EmployeeId_IsManualOverride_Date",
                table: "DaySettings",
                columns: new[] { "EmployeeId", "IsManualOverride", "Date" });

            migrationBuilder.CreateIndex(
                name: "IX_BalanceTransfers_EmployeeId_FromDay",
                table: "BalanceTransfers",
                columns: new[] { "EmployeeId", "FromDay" });

            migrationBuilder.CreateIndex(
                name: "IX_BalanceTransfers_EmployeeId_ToDay",
                table: "BalanceTransfers",
                columns: new[] { "EmployeeId", "ToDay" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Events_EmployeeId_IsAutoGenerated_AutoGeneratedForDate",
                table: "Events");

            migrationBuilder.DropIndex(
                name: "IX_Events_EmployeeId_IsDeleted_EndTime",
                table: "Events");

            migrationBuilder.DropIndex(
                name: "IX_Events_EmployeeId_IsDeleted_ImportBatchId",
                table: "Events");

            migrationBuilder.DropIndex(
                name: "IX_Events_EmployeeId_IsDeleted_StartTime",
                table: "Events");

            migrationBuilder.DropIndex(
                name: "IX_Events_EmployeeId_ParentEventId",
                table: "Events");

            migrationBuilder.DropIndex(
                name: "IX_DaySettings_EmployeeId_IsManualOverride_Date",
                table: "DaySettings");

            migrationBuilder.DropIndex(
                name: "IX_BalanceTransfers_EmployeeId_FromDay",
                table: "BalanceTransfers");

            migrationBuilder.DropIndex(
                name: "IX_BalanceTransfers_EmployeeId_ToDay",
                table: "BalanceTransfers");

            migrationBuilder.CreateIndex(
                name: "IX_Events_AutoGeneratedForDate",
                table: "Events",
                column: "AutoGeneratedForDate");

            migrationBuilder.CreateIndex(
                name: "IX_Events_EmployeeId",
                table: "Events",
                column: "EmployeeId");

            migrationBuilder.CreateIndex(
                name: "IX_Events_StartTime",
                table: "Events",
                column: "StartTime");
        }
    }
}
