// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeacherScheduleApp.Data;

#nullable disable

namespace TeacherScheduleApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419193607_OptimizeQueriesAndIndexes")]
    partial class OptimizeQueriesAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TeacherScheduleApp.Models.BalanceSelfTrim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<int>("Edge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Day", "Edge")
                        .IsUnique();

                    b.ToTable("BalanceSelfTrims");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.BalanceTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Edge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FromDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToDay")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "FromDay");

                    b.HasIndex("EmployeeId", "ToDay");

                    b.HasIndex("EmployeeId", "FromDay", "ToDay", "Edge")
                        .IsUnique();

                    b.ToTable("BalanceTransfers");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.DaySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LunchEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LunchStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "IsManualOverride", "Date");

                    b.ToTable("DaySettings");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoGeneratedForDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCollision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("ParentEventId");

                    b.HasIndex("EmployeeId", "ParentEventId");

                    b.HasIndex("EmployeeId", "IsAutoGenerated", "AutoGeneratedForDate");

                    b.HasIndex("EmployeeId", "IsDeleted", "EndTime");

                    b.HasIndex("EmployeeId", "IsDeleted", "ImportBatchId");

                    b.HasIndex("EmployeeId", "IsDeleted", "StartTime");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.ImportBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.SemesterSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AutoEventNameLunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoEventNamePostLunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoEventNamePreLunch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalEndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalStartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxBreakDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinBreakDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Semester")
                        .IsUnique();

                    b.ToTable("SemesterSettings");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.WeekdaySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LunchEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LunchStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SemesterSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SemesterSettingsId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WeekdaySettings");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.DaySettings", b =>
                {
                    b.HasOne("TeacherScheduleApp.Models.Employee", "Employee")
                        .WithMany("DaySettings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.Event", b =>
                {
                    b.HasOne("TeacherScheduleApp.Models.Employee", "Employee")
                        .WithMany("Events")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherScheduleApp.Models.ImportBatch", "ImportBatch")
                        .WithMany("Events")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeacherScheduleApp.Models.Event", "ParentEvent")
                        .WithMany("Children")
                        .HasForeignKey("ParentEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("ImportBatch");

                    b.Navigation("ParentEvent");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.SemesterSettings", b =>
                {
                    b.HasOne("TeacherScheduleApp.Models.Employee", "Employee")
                        .WithMany("SemesterSettings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.WeekdaySettings", b =>
                {
                    b.HasOne("TeacherScheduleApp.Models.SemesterSettings", "SemesterSettings")
                        .WithMany("WeekdaySettings")
                        .HasForeignKey("SemesterSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SemesterSettings");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.Employee", b =>
                {
                    b.Navigation("DaySettings");

                    b.Navigation("Events");

                    b.Navigation("SemesterSettings");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.Event", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.ImportBatch", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TeacherScheduleApp.Models.SemesterSettings", b =>
                {
                    b.Navigation("WeekdaySettings");
                });
#pragma warning restore 612, 618
        }
    }
}
