using System;
using System.Globalization;
using Avalonia.Data.Converters;
using Avalonia.Media;
using TeacherScheduleApp.Models;

namespace TeacherScheduleApp.Converters
{
    public class EventBrushConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value is not Event ev)
                return Brushes.Gray;

            if (ev.EventType == EventType.Lunch)
                return ev.HasCollision ? Brushes.Red : Brushes.Orange;
            if (!ev.IsAutoGenerated && ev.HasCollision)
                return Brushes.Red;
            if (ev.EventType == EventType.Work)
                return Brushes.SteelBlue;
            return Brushes.Gray;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
            => throw new NotImplementedException();
    }
}
