using System;
using System.Collections.Generic;
using System.Globalization;
using Avalonia.Data.Converters;
using Avalonia.Media;
using TeacherScheduleApp.Models;

namespace TeacherScheduleApp.Converters
{
    public class EventBrushConverter : IValueConverter
    {
        public object Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (value is not Event ev) return Brushes.Gray;

            if (ev.EventType == EventType.Lunch)
                return ev.HasCollision ? Brushes.Red : Brushes.Orange;

            if (ev.EventType == EventType.Work)
                return (!ev.IsAutoGenerated && ev.HasCollision) ? Brushes.Red : Brushes.SteelBlue;

            if (ev.EventType == EventType.Teaching)
                return (!ev.IsAutoGenerated && ev.HasCollision) ? Brushes.Red : Brushes.MediumVioletRed;

            if (IsSpecial(ev.EventType))
                return SpecialBrush(ev.EventType);

            return Brushes.Gray;
        }

        public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture) => throw new NotImplementedException();
        private static readonly HashSet<EventType> SpecialTypes = new()
        {
            EventType.DayOff, EventType.Illness, EventType.Vacation,
            EventType.Ocr, EventType.Doctor, EventType.BusinessTrip, EventType.Holiday
        };
        private static bool IsSpecial(EventType t) => SpecialTypes.Contains(t);
        private static IBrush SpecialBrush(EventType t) => t switch
        {
            EventType.Vacation => Brushes.MediumSeaGreen,
            EventType.Illness => Brushes.MediumOrchid,
            EventType.DayOff => Brushes.SlateGray,
            EventType.Ocr => Brushes.DarkOrange,
            EventType.Doctor => Brushes.SeaGreen,
            EventType.BusinessTrip => Brushes.SteelBlue,
            EventType.Holiday => Brushes.Goldenrod,
            EventType.Teaching => Brushes.MediumVioletRed,
            _ => Brushes.Gray
        };
    }
}
