using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;

namespace TeacherScheduleApp.Models
{
    public class Event
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public int EmployeeId { get; set; }
        public int? ParentEventId { get; set; }

        public string Title { get; set; } = string.Empty;
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public bool AllDay { get; set; }
        public string? Description { get; set; }
        public bool IsDeleted { get; set; }

        public EventType EventType { get; set; } = EventType.Work;
        public bool IsAutoGenerated { get; set; }
        public bool HasCollision { get; set; }
        public DateTime? AutoGeneratedForDate { get; set; }

        public string? ImportBatchId { get; set; }

        [NotMapped]
        public bool IsInactive { get; set; }

        [NotMapped]
        public double StartHour => StartTime.Hour + StartTime.Minute / 60.0;

        [NotMapped]
        public double EndHour => EndTime.Hour + EndTime.Minute / 60.0;

        [NotMapped]
        public double DurationHours
        {
            get
            {
                var hours = (EndTime - StartTime).TotalHours;
                return hours < 0 ? 0 : hours;
            }
        }

        public Employee Employee { get; set; } = null!;
        public Event? ParentEvent { get; set; }
        public ICollection<Event> Children { get; set; } = new List<Event>();
        public ImportBatch? ImportBatch { get; set; }
    }

    public enum EventType
    {
        [Display(Name = "Práce")]
        Work,

        [Display(Name = "Oběd")]
        Lunch,

        [Display(Name = "Volno")]
        DayOff,

        [Display(Name = "Nemoc")]
        Illness,

        [Display(Name = "Dovolená")]
        Vacation,

        [Display(Name = "Ošetřování")]
        Ocr,

        [Display(Name = "Lékař")]
        Doctor,

        [Display(Name = "Pracovní cesta")]
        BusinessTrip,

        [Display(Name = "Svátek")]
        Holiday,

        [Display(Name = "Výuka")]
        Teaching,
    }

    public static class EventTypeExtensions
    {
        public static bool IsAutoAdjustableWork(this EventType type)
            => type is EventType.Work;

        public static bool IsTeaching(this EventType type)
            => type == EventType.Teaching;

        public static bool IsCreditedWorkTime(this EventType type)
            => type.IsAutoAdjustableWork() || type.IsTeaching();

        public static bool IsSpecialAbsence(this EventType type)
            => type != EventType.Lunch && !type.IsCreditedWorkTime();

        public static int GetOverlayPriority(this EventType type) => type switch
        {
            EventType.DayOff => 400,
            EventType.Illness => 400,
            EventType.Vacation => 400,
            EventType.Ocr => 400,
            EventType.Doctor => 400,
            EventType.Holiday => 400,
            EventType.Teaching => 300,
            EventType.BusinessTrip => 200,
            EventType.Work => 100,
            _ => 0
        };

        public static bool ShouldShowCollisionAgainst(this EventType current, EventType other)
        {
            if (current == EventType.Lunch)
                return other != EventType.Lunch;

            if (other == EventType.Lunch)
                return true;

            if (current.IsTeaching() && other.IsTeaching())
                return false;

            var currentPriority = current.GetOverlayPriority();
            var otherPriority = other.GetOverlayPriority();

            if (currentPriority < otherPriority)
                return true;

            if (currentPriority > otherPriority)
                return false;

            return true;
        }

        public static string ToDisplayName(this EventType type)
        {
            var member = type.GetType()
                             .GetMember(type.ToString())
                             .FirstOrDefault();

            if (member != null)
            {
                var disp = member.GetCustomAttribute<DisplayAttribute>();
                if (disp?.Name != null)
                    return disp.Name;
            }

            return type.ToString();
        }
    }
}
