using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;

namespace TeacherScheduleApp.Models
{
    public class Event
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public int EmployeeId { get; set; }
        public int? ParentEventId { get; set; }

        public string Title { get; set; } = string.Empty;
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public bool AllDay { get; set; }
        public string? Description { get; set; }
        public bool IsDeleted { get; set; }

        public EventType EventType { get; set; } = EventType.Work;
        public bool IsAutoGenerated { get; set; }
        public bool HasCollision { get; set; }
        public DateTime? AutoGeneratedForDate { get; set; }

        public string? ImportBatchId { get; set; }

        [NotMapped]
        public bool IsInactive { get; set; }

        [NotMapped]
        public double StartHour => StartTime.Hour + StartTime.Minute / 60.0;

        [NotMapped]
        public double EndHour => EndTime.Hour + EndTime.Minute / 60.0;

        [NotMapped]
        public double DurationHours
        {
            get
            {
                var hours = (EndTime - StartTime).TotalHours;
                return hours < 0 ? 0 : hours;
            }
        }

        public Employee Employee { get; set; } = null!;
        public Event? ParentEvent { get; set; }
        public ICollection<Event> Children { get; set; } = new List<Event>();
        public ImportBatch? ImportBatch { get; set; }
    }

    public enum EventType
    {
        [Display(Name = "Práce")]
        Work,

        [Display(Name = "Oběd")]
        Lunch,

        [Display(Name = "Volno")]
        DayOff,

        [Display(Name = "Nemoc")]
        Illness,

        [Display(Name = "Dovolená")]
        Vacation,

        [Display(Name = "Ošetřování")]
        Ocr,

        [Display(Name = "Lékař")]
        Doctor,

        [Display(Name = "Pracovní cesta")]
        BusinessTrip,

        [Display(Name = "Svátek")]
        Holiday,
    }

    public static class EventTypeExtensions
    {
        public static string ToDisplayName(this EventType type)
        {
            var member = type.GetType()
                             .GetMember(type.ToString())
                             .FirstOrDefault();

            if (member != null)
            {
                var disp = member.GetCustomAttribute<DisplayAttribute>();
                if (disp?.Name != null)
                    return disp.Name;
            }

            return type.ToString();
        }
    }
}