using MsBox.Avalonia.Enums;
using MsBox.Avalonia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeacherScheduleApp.Models;
using TeacherScheduleApp.ViewModels;
using Avalonia.Controls.Documents;
using ReactiveUI;
using TeacherScheduleApp.Messages;
using static TeacherScheduleApp.Models.GlobalSettings;
using TeacherScheduleApp.Helpers;
using System.Globalization;
using DynamicData.Aggregation;

namespace TeacherScheduleApp.Services
{

    public class AutomaticEventsGeneratorService
    {
        private readonly EventService _eventService;
        private readonly Func<string, Task<bool>> _askCollision;
        private bool? _moveAllLunchesForAllDays = null;
        public AutomaticEventsGeneratorService(EventService eventService, Func<string, Task<bool>> askCollision)
        {
            _eventService = eventService;
            _askCollision = askCollision;
        }

        public SemesterType GetSemesterForDate(DateTime date)
        {
            if ((date.Month >= 9) || (date.Month == 2 && date.Day <= 9))
            {
                return SemesterType.Winter;
            }

            if (date.Month >= 2 && date.Month <= 8)
            {
                return SemesterType.Summer;
            }

            return SemesterType.Winter;
        }
        public async Task RegenerateAllAutoEventsForSemester(GlobalSettings.SemesterType sem)
        {
            var allDates = _eventService
                .GetAllEvents()
                .Where(e => e.IsAutoGenerated
                            && e.AutoGeneratedForDate.HasValue
                            && GetSemesterForDate(e.AutoGeneratedForDate.Value) == sem)
                .Select(e => e.AutoGeneratedForDate.Value.Date)
                .Distinct()
                .OrderBy(d => d)
                .ToList();

            foreach (var date in allDates)
                await RegenerateDailyEventsAsync(date);
        }
        private void CreateAuto(DateTime start, DateTime end, EventType type, string title)
        {
            _eventService.CreateEvent(new Event
            {
                Title = title,
                StartTime = start,
                EndTime = end,
                EventType = type,
                IsAutoGenerated = true,
                AutoGeneratedForDate = start.Date
            });
        }

        public async Task RegenerateDailyEventsAsync(DateTime date)
        {
            var day = date.Date;
            var dayStart = day;
            var dayEnd = day.AddDays(1);

            _eventService.RemoveAutoGeneratedEvents(day);

            static (DateTime S, DateTime E) ClipToDay(DateTime dayStart, DateTime dayEnd, DateTime s, DateTime e)
            {
                var cs = s < dayStart ? dayStart : s;
                var ce = e > dayEnd ? dayEnd : e;
                return ce > cs ? (cs, ce) : (cs, cs);
            }

            if (HolidayHelper.IsCzechHoliday(day) || day.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday)
            {
                var manualFullDay = _eventService
                    .GetEventsForDay(day)
                    .Where(e => !e.IsAutoGenerated && e.AllDay && e.EventType is not EventType.Work and not EventType.Lunch)
                    .ToList();
                foreach (var ev in manualFullDay)
                    _eventService.DeleteEvent(ev.Id);
                return;
            }

            var manualRaw = _eventService
                .GetEventsForDay(day)
                .Where(e => !e.IsAutoGenerated)
                .OrderBy(e => e.StartTime)
                .ToList();

            var manual = manualRaw
                .Select(e =>
                {
                    var c = ClipToDay(dayStart, dayEnd, e.StartTime, e.EndTime);
                    return new { Event = e, S = c.S, E = c.E };
                })
                .Where(x => x.E > x.S)
                .ToList();

            for (int i = 0; i < manual.Count; i++)
                for (int j = i + 1; j < manual.Count; j++)
                    if (Overlaps(manual[i].S.TimeOfDay, manual[i].E.TimeOfDay, manual[j].S.TimeOfDay, manual[j].E.TimeOfDay))
                    {
                        manual[j].Event.HasCollision = true;
                        _eventService.UpdateEvent(manual[j].Event);
                    }

            var sem = GetSemesterForDate(day);
            var global = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                         ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var user = SettingsService.GetUserSettingsForDate(day);

            TimeSpan gStart = TimeSpan.Parse(global.GlobalStartTime, CultureInfo.InvariantCulture);
            TimeSpan gEnd = TimeSpan.Parse(global.GlobalEndTime, CultureInfo.InvariantCulture);
            TimeSpan dStart = user?.ArrivalTime ?? gStart;
            TimeSpan dEnd = user?.DepartureTime ?? gEnd;

            TimeSpan defArr, defDep, defLS, defLE;
            (defArr, defDep, defLS, defLE) = PdfService.GetWeekdayDefaults(global, day.DayOfWeek);

            var arrival = day + dStart;
            var departure = day + dEnd;

            var lunchStart = user is null ? day + defLS : day + user.LunchStart;
            var lunchEnd = user is null ? day + defLE : day + user.LunchEnd;
            if (lunchStart < arrival) lunchStart = arrival;
            if (lunchEnd > departure) lunchEnd = departure;

            var specials = manual
                .Where(x => x.Event.EventType != EventType.Work && x.Event.EventType != EventType.Lunch)
                .Select(x => (S: x.S, E: x.E, T: x.Event.EventType))
                .ToList();

            TimeSpan IntersectLen((DateTime S, DateTime E, EventType T) e)
            {
                var s = e.S < day + defArr ? day + defArr : e.S;
                var ee = e.E > day + defDep ? day + defDep : e.E;
                return ee > s ? (ee - s) : TimeSpan.Zero;
            }

            var eight = TimeSpan.FromHours(8);
            var gross = defDep - defArr;
            var netNorm = gross - (defLE - defLS);
            if (netNorm < TimeSpan.Zero) netNorm = TimeSpan.Zero;

            bool fullSpecialDay =
                specials.Any(sp => sp.T == EventType.Vacation && IntersectLen(sp) >= eight) ||
                specials.Any(sp => sp.T != EventType.Vacation && IntersectLen(sp) >= netNorm);

            if (fullSpecialDay)
            {
                foreach (var e in _eventService.GetEventsForDay(day)
                             .Where(e => e.EventType == EventType.Lunch && !e.IsAutoGenerated)
                             .ToList())
                    _eventService.DeleteEvent(e.Id);

                SaveUserSettingsFromEvents(day);
                return;
            }

            var overlapping = manual.Where(l => Overlaps(lunchStart.TimeOfDay, lunchEnd.TimeOfDay, l.S.TimeOfDay, l.E.TimeOfDay)).ToList();
            bool lunchCollision = overlapping.Any();

            if (lunchCollision)
            {
                if (!_moveAllLunchesForAllDays.HasValue)
                {
                    _moveAllLunchesForAllDays = await _askCollision($"Oběd {lunchStart:hh\\:mm}-{lunchEnd:hh\\:mm} se překrývá s události. Přesunout všechny obědy s kolizemi hned?");
                }
                if (_moveAllLunchesForAllDays.Value)
                {
                    var lastEnd = overlapping.Max(l => l.E.TimeOfDay);
                    var duration = lunchEnd - lunchStart;
                    lunchStart = day + lastEnd;
                    lunchEnd = lunchStart + duration;
                }
                else
                {
                    var std = lunchEnd - lunchStart;
                    foreach (var m in overlapping)
                    {
                        var ok = await _askCollision($"Oběd {lunchStart:HH\\:mm}-{lunchEnd:HH\\:mm} se překrývá s událostí “{m.Event.Title}” dne {m.S:dd.MM.yyyy} ({m.S:HH\\:mm}-{m.E:HH\\:mm}). Přesunout oběd hned po této události?");
                        if (!ok) continue;
                        lunchStart = day + m.E.TimeOfDay;
                        lunchEnd = lunchStart + std;
                    }
                }
            }

            if (manual.Any())
            {
                var first = manual.Min(l => l.S);
                var last = manual.Max(l => l.E);
                if (first < arrival) arrival = first;
                if (last > departure) departure = last;
            }

            var target = (defDep - defArr) - (defLE - defLS);
            if (target < TimeSpan.Zero) target = TimeSpan.Zero;
            double targetHours = target.TotalHours;

            var mergedManualNoLunch = MergeIntervals(
                manual.Where(e => e.Event.EventType != EventType.Lunch)
                      .Select(e => (Start: e.S, End: e.E))
                      .ToList()
            );
            double manualHoursAll = mergedManualNoLunch.Sum(seg => (seg.end - seg.start).TotalHours);

            var newEvents = new List<Event>();

            bool lunchHitsSpecial = specials.Any(sp =>
                Overlaps((day + (user?.LunchStart ?? defLS)).TimeOfDay,
                         (day + (user?.LunchEnd ?? defLE)).TimeOfDay,
                         sp.S.TimeOfDay, sp.E.TimeOfDay));

            if (!lunchHitsSpecial && lunchEnd > lunchStart)
            {
                newEvents.Add(new Event
                {
                    Title = global.AutoEventNameLunch,
                    StartTime = lunchStart,
                    EndTime = lunchEnd,
                    EventType = EventType.Lunch,
                    IsAutoGenerated = true,
                    AutoGeneratedForDate = day,
                    HasCollision = lunchCollision
                });
            }

            if (manualHoursAll >= targetHours - 1e-6)
            {
                foreach (var ev in newEvents) _eventService.CreateAutoEvent(ev);
                SaveUserSettingsFromEvents(day);
                return;
            }

            var busyCandidates = new List<(DateTime Start, DateTime End)>();
            busyCandidates.AddRange(manual.Select(l => (l.S, l.E)));
            if (newEvents.Any(e => e.EventType == EventType.Lunch))
            {
                var ln = newEvents.First(e => e.EventType == EventType.Lunch);
                busyCandidates.Add((ln.StartTime, ln.EndTime));
            }

            var busy = MergeIntervals(busyCandidates);

            var gaps = new List<(DateTime s, DateTime e)>();
            var cursor = arrival;
            foreach (var b in busy)
            {
                if (cursor >= departure) break;
                var gapEnd = Min(b.start, departure);
                if (gapEnd > cursor) gaps.Add((cursor, gapEnd));
                cursor = Max(cursor, b.end);
            }
            if (cursor < departure) gaps.Add((cursor, departure));

            foreach (var (s, e) in gaps)
            {
                if (e <= s) continue;
                newEvents.Add(new Event
                {
                    Title = (newEvents.Any(x => x.EventType == EventType.Lunch) && s >= newEvents.First(x => x.EventType == EventType.Lunch).EndTime)
                        ? global.AutoEventNamePostLunch
                        : global.AutoEventNamePreLunch,
                    StartTime = s,
                    EndTime = e,
                    EventType = EventType.Work,
                    IsAutoGenerated = true,
                    AutoGeneratedForDate = day
                });
            }

            var autoWork = newEvents.Where(e => e.EventType == EventType.Work).ToList();
            double autoHours = autoWork.Sum(e => (e.EndTime - e.StartTime).TotalHours);
            double over = (manualHoursAll + autoHours) - targetHours;

            if (over > 1e-6)
            {
                DateTime firstBusyStart = busy.Count > 0 ? busy[0].start : departure;
                DateTime lastBusyEnd = busy.Count > 0 ? busy[^1].end : arrival;

                var leftEdge = autoWork
                    .Where(e => e.EndTime <= firstBusyStart)
                    .OrderBy(e => e.StartTime)
                    .ToList();
                foreach (var ev in leftEdge)
                {
                    if (over <= 1e-6) break;
                    var span = (ev.EndTime - ev.StartTime).TotalHours;
                    var cut = Math.Min(span, over);
                    ev.StartTime += TimeSpan.FromHours(cut);
                    over -= cut;
                    if (ev.EndTime <= ev.StartTime + TimeSpan.FromMinutes(1))
                        newEvents.Remove(ev);
                }

                if (over > 1e-6)
                {
                    var rightEdge = autoWork
                        .Where(e => e.StartTime >= lastBusyEnd)
                        .OrderByDescending(e => e.EndTime)
                        .ToList();
                    foreach (var ev in rightEdge)
                    {
                        if (over <= 1e-6) break;
                        var span = (ev.EndTime - ev.StartTime).TotalHours;
                        var cut = Math.Min(span, over);
                        ev.EndTime -= TimeSpan.FromHours(cut);
                        over -= cut;
                        if (ev.EndTime <= ev.StartTime + TimeSpan.FromMinutes(1))
                            newEvents.Remove(ev);
                    }
                }

                if (over > 1e-6)
                {
                    var autos = newEvents
                        .Where(e => e.EventType == EventType.Work)
                        .OrderBy(e => e.StartTime)
                        .ToList();
                    foreach (var ev in autos)
                    {
                        if (over <= 1e-6) break;
                        var span = (ev.EndTime - ev.StartTime).TotalHours;
                        var cut = Math.Min(span, over);
                        ev.StartTime += TimeSpan.FromHours(cut);
                        over -= cut;
                        if (ev.EndTime <= ev.StartTime + TimeSpan.FromMinutes(1))
                            newEvents.Remove(ev);
                    }
                }
            }

            foreach (var ev in newEvents.Where(e => e.EventType == EventType.Work))
                ev.Title = (newEvents.Any(x => x.EventType == EventType.Lunch) && ev.StartTime >= newEvents.First(x => x.EventType == EventType.Lunch).EndTime)
                    ? global.AutoEventNamePostLunch
                    : global.AutoEventNamePreLunch;

            foreach (var ev in newEvents)
                _eventService.CreateAutoEvent(ev);

            SaveUserSettingsFromEvents(day);
        }




        private void SaveUserSettingsFromEvents(DateTime day)
        {
            var evs = _eventService.GetEventsForDay(day)
                        .Where(e => !e.IsDeleted)
                        .OrderBy(e => e.StartTime)
                        .ToList();

            var sem = GetSemesterForDate(day);
            var global = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                         ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(global, day.DayOfWeek);

            var existingUser = SettingsService.GetUserSettingsForDate(day);

            if (!evs.Any())
            {
                if (existingUser == null)
                    SettingsService.SaveUserSettingsForDate(day, defArr, defDep, defLs, defLe);
                return;
            }

            TimeSpan gross = defDep - defArr;
            var netNorm = gross - (defLe - defLs);
            if (netNorm < TimeSpan.Zero) netNorm = TimeSpan.Zero;
            var eight = TimeSpan.FromHours(8);

            bool IsSpecial(Event e) => e.EventType != EventType.Work && e.EventType != EventType.Lunch;

            var specials = evs.Where(IsSpecial).ToList();

            bool fullSpecialDay =
                specials.Any(e => e.AllDay) ||
                specials.Any(e => e.StartTime.TimeOfDay <= defArr && e.EndTime.TimeOfDay >= defDep) ||
                specials.Any(e =>
                {
                    var len = e.EndTime - e.StartTime;
                    return e.EventType == EventType.Vacation ? len >= eight : len >= netNorm;
                });

            if (fullSpecialDay)
            {
                var start = specials.Min(e => e.StartTime).TimeOfDay;
                var end = specials.Max(e => e.EndTime).TimeOfDay;
                SettingsService.SaveUserSettingsForDate(day, start, end, TimeSpan.Zero, TimeSpan.Zero);
                return;
            }


            var manualWL = evs.Where(e => !e.IsAutoGenerated && (e.EventType == EventType.Work || e.EventType == EventType.Lunch)).ToList();

            var arrival = defArr;
            var departure = defDep;
            if (manualWL.Any())
            {
                var minStart = manualWL.Min(e => e.StartTime).TimeOfDay;
                var maxEnd = manualWL.Max(e => e.EndTime).TimeOfDay;
                if (minStart < arrival) arrival = minStart;
                if (maxEnd > departure) departure = maxEnd;
            }

            TimeSpan ls, le;
            var lunchManual = manualWL.FirstOrDefault(e => e.EventType == EventType.Lunch);
            if (lunchManual != null)
            {
                ls = lunchManual.StartTime.TimeOfDay;
                le = lunchManual.EndTime.TimeOfDay;
            }
            else
            {
                var lunchNonAuto = evs.FirstOrDefault(e => !e.IsAutoGenerated && e.EventType == EventType.Lunch);
                if (lunchNonAuto != null)
                {
                    ls = lunchNonAuto.StartTime.TimeOfDay;
                    le = lunchNonAuto.EndTime.TimeOfDay;
                }
                else
                {
                    ls = defLs;
                    le = defLe;
                }
            }

            SettingsService.SaveUserSettingsForDate(day, arrival, departure, ls, le);
        }


        private static bool Overlaps(TimeSpan a0, TimeSpan a1, TimeSpan b0, TimeSpan b1)
            => a0 < b1 && b0 < a1;

        private (TimeSpan arr, TimeSpan dep, TimeSpan lunchStart, TimeSpan lunchEnd)
        GetDaySpans(GlobalSettings g, UserSettings u, DayOfWeek wd)
        {
            string sa, sd, s0, s1;
            switch (wd)
            {
                case DayOfWeek.Monday:
                    (sa, sd, s0, s1) =
                      (g.MondayArrival, g.MondayDeparture,
                       g.MondayLunchStart, g.MondayLunchEnd);
                    break;
                case DayOfWeek.Tuesday:
                    (sa, sd, s0, s1) =
                      (g.TuesdayArrival, g.TuesdayDeparture,
                       g.TuesdayLunchStart, g.TuesdayLunchEnd);
                    break;
                case DayOfWeek.Wednesday:
                    (sa, sd, s0, s1) =
                      (g.WednesdayArrival, g.WednesdayDeparture,
                       g.WednesdayLunchStart, g.WednesdayLunchEnd);
                    break;
                case DayOfWeek.Thursday:
                    (sa, sd, s0, s1) =
                      (g.ThursdayArrival, g.ThursdayDeparture,
                       g.ThursdayLunchStart, g.ThursdayLunchEnd);
                    break;
                case DayOfWeek.Friday:
                    (sa, sd, s0, s1) =
                      (g.FridayArrival, g.FridayDeparture,
                       g.FridayLunchStart, g.FridayLunchEnd);
                    break;
                default:
                    throw new InvalidOperationException("Není pracovný den");
            }

            if (u != null)
            {
                sa = u.ArrivalTime.ToString(@"hh\:mm");
                sd = u.DepartureTime.ToString(@"hh\:mm");
                s0 = u.LunchStart.ToString(@"hh\:mm");
                s1 = u.LunchEnd.ToString(@"hh\:mm");
            }
            if (string.IsNullOrWhiteSpace(sa) || string.IsNullOrWhiteSpace(sd))
            {
                sa = g.GlobalStartTime;
                sd = g.GlobalEndTime;
            }

            var arr = TimeSpan.Parse(sa, CultureInfo.InvariantCulture);
            var dep = TimeSpan.Parse(sd, CultureInfo.InvariantCulture);


            TimeSpan lunchStart, lunchEnd;
            if (string.IsNullOrWhiteSpace(s0) || string.IsNullOrWhiteSpace(s1))
            {
                var halfSpan = (dep - arr) / 2;
                lunchStart = arr + halfSpan - TimeSpan.FromMinutes(15);
                lunchEnd = lunchStart + TimeSpan.FromMinutes(30);
            }
            else
            {
                lunchStart = TimeSpan.Parse(s0, CultureInfo.InvariantCulture);
                lunchEnd = TimeSpan.Parse(s1, CultureInfo.InvariantCulture);
            }


            return (arr, dep, lunchStart, lunchEnd);
        }
        static DateTime Min(DateTime a, DateTime b) => a < b ? a : b;
        static DateTime Max(DateTime a, DateTime b) => a > b ? a : b;

        public async Task RegenerateRangeEventsAsync(DateTime start, DateTime end)
        {
            _moveAllLunchesForAllDays = null;
            for (var d = start.Date; d <= end.Date; d = d.AddDays(1))
                await RegenerateDailyEventsAsync(d);

            MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
        }
        private bool IsInVacation(DateTime day, out GlobalSettings global)
        {
            var sem = GetSemesterForDate(day);
            global = GlobalSettingsService
                        .LoadGlobalSettings(day.Year,sem)
                     ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);

            int md = day.Month * 100 + day.Day;

            int winterStart = 12 * 100 + 23;
            int winterEnd = 1 * 100 + 1;
            bool inWinter = (md >= winterStart) || (md <= winterEnd);

            int summerStart = 6 * 100 + 30;
            int summerEnd = 8 * 100 + 10;
            bool inSummer = md >= summerStart && md <= summerEnd;

            return inWinter || inSummer;
        }
        private List<(DateTime start, DateTime end)> MergeIntervals(List<(DateTime start, DateTime end)> intervals)
        {
            var sorted = intervals.OrderBy(x => x.start).ToList();
            var merged = new List<(DateTime start, DateTime end)>();
            foreach (var seg in sorted)
            {
                if (merged.Count == 0 || merged[^1].end < seg.start)
                    merged.Add(seg);
                else
                    merged[^1] = (
                        merged[^1].start,
                        merged[^1].end > seg.end ? merged[^1].end : seg.end
                    );
            }
            return merged;
        }
        private static double OverlapHours(DateTime segStart, DateTime segEnd,
                                   List<(DateTime start, DateTime end)> intervals)
        {
            double sum = 0;
            foreach (var iv in intervals)
            {
                var s = segStart > iv.start ? segStart : iv.start;
                var e = segEnd < iv.end ? segEnd : iv.end;
                if (e > s) sum += (e - s).TotalHours;
            }
            return sum;
        }
    }
}
