using MsBox.Avalonia.Enums;
using MsBox.Avalonia;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeacherScheduleApp.Models;
using TeacherScheduleApp.ViewModels;
using Avalonia.Controls.Documents;
using ReactiveUI;
using TeacherScheduleApp.Messages;
using static TeacherScheduleApp.Models.GlobalSettings;
using TeacherScheduleApp.Helpers;
using System.Globalization;
using DynamicData.Aggregation;
using TeacherScheduleApp.Data;

namespace TeacherScheduleApp.Services
{

    public class AutomaticEventsGeneratorService
    {
        private readonly EventService _eventService;
        private readonly Func<string, Task<bool>> _askCollision;
        private bool? _moveAllLunchesForAllDays = null;
        public AutomaticEventsGeneratorService(EventService eventService, Func<string, Task<bool>> askCollision)
        {
            _eventService = eventService;
            _askCollision = askCollision;
        }

        public SemesterType GetSemesterForDate(DateTime date)
        {
            if ((date.Month >= 9) || (date.Month == 2 && date.Day <= 9))
            {
                return SemesterType.Winter;
            }

            if (date.Month >= 2 && date.Month <= 8)
            {
                return SemesterType.Summer;
            }

            return SemesterType.Winter;
        }
        public async Task RegenerateAllAutoEventsForSemester(GlobalSettings.SemesterType sem)
        {
            var allDates = _eventService
                .GetAllEvents()
                .Where(e => e.IsAutoGenerated
                            && e.AutoGeneratedForDate.HasValue
                            && GetSemesterForDate(e.AutoGeneratedForDate.Value) == sem)
                .Select(e => e.AutoGeneratedForDate.Value.Date)
                .Distinct()
                .OrderBy(d => d)
                .ToList();

            foreach (var date in allDates)
                await RegenerateDailyEventsAsync(date);
        }
        private void CreateAuto(DateTime start, DateTime end, EventType type, string title)
        {
            _eventService.CreateEvent(new Event
            {
                Title = title,
                StartTime = start,
                EndTime = end,
                EventType = type,
                IsAutoGenerated = true,
                AutoGeneratedForDate = start.Date
            });
        }

        public async Task RegenerateDailyEventsAsync(DateTime date, bool preserveUserSettings = false)
        {
            var day = date.Date;
            var dayStart = day;
            var dayEnd = day.AddDays(1);
            var calc = new WorkingHoursCalculatorService();
            _eventService.RemoveAutoGeneratedEvents(day);

            static (DateTime S, DateTime E) ClipToDay(DateTime ds, DateTime de, DateTime s, DateTime e)
            {
                var cs = s < ds ? ds : s;
                var ce = e > de ? de : e;
                return ce > cs ? (cs, ce) : (cs, cs);
            }

            if (HolidayHelper.IsCzechHoliday(day) || day.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday)
            {
                var manualFullDay = _eventService
                    .GetEventsForDay(day)
                    .Where(e => !e.IsAutoGenerated && e.AllDay && e.EventType is not EventType.Work and not EventType.Lunch)
                    .ToList();
                foreach (var ev in manualFullDay)
                    _eventService.DeleteEvent(ev.Id);
                return;
            }

            var manualRaw = _eventService
                .GetEventsForDay(day)
                .Where(e => !e.IsAutoGenerated)
                .OrderBy(e => e.StartTime)
                .ToList();

            var manual = manualRaw
                .Select(e =>
                {
                    var c = ClipToDay(dayStart, dayEnd, e.StartTime, e.EndTime);
                    return new { Event = e, S = c.S, E = c.E };
                })
                .Where(x => x.E > x.S)
                .ToList();

            for (int i = 0; i < manual.Count; i++)
                for (int j = i + 1; j < manual.Count; j++)
                    if (Overlaps(manual[i].S.TimeOfDay, manual[i].E.TimeOfDay, manual[j].S.TimeOfDay, manual[j].E.TimeOfDay))
                    {
                        manual[j].Event.HasCollision = true;
                        _eventService.UpdateEvent(manual[j].Event, suppressRegen: true);
                    }

            var sem = GetSemesterForDate(day);
            var global = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                         ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var user = SettingsService.GetUserSettingsForDate(day);
            var (defArr, defDep, defLS, defLE) = PdfService.GetWeekdayDefaults(global, day.DayOfWeek);

            var arrival = day + (user?.ArrivalTime ?? defArr);
            var departure = day + (user?.DepartureTime ?? defDep);

            var lunchStart = day + (user?.LunchStart ?? defLS);
            var lunchEnd = day + (user?.LunchEnd ?? defLE);

            var manualLunch = manual.FirstOrDefault(x => x.Event.EventType == EventType.Lunch);
            if (manualLunch != null)
            {
                lunchStart = manualLunch.S;
                lunchEnd = manualLunch.E;
            }

            var manualWork = manual.Where(x => x.Event.EventType == EventType.Work || x.Event.EventType == EventType.BusinessTrip).ToList();
            if (manualWork.Any())
            {
                var first = manualWork.Min(x => x.S);
                var last = manualWork.Max(x => x.E);
                if (first < arrival) arrival = first;
                if (last > departure) departure = last;
            }

            if (lunchStart < arrival) lunchStart = arrival;
            if (lunchEnd > departure) lunchEnd = departure;

            bool userWantsLunch = user == null ? true : user.LunchStart != user.LunchEnd;
            bool canCreateAutoLunch = manualLunch == null && userWantsLunch;

            bool hasValidLunch = false;
            bool overlapsManual = false;


            var specials = manual
                .Where(x => x.Event.EventType != EventType.Work && x.Event.EventType != EventType.Lunch)
                .Select(x => (S: x.S, E: x.E, T: x.Event.EventType))
                .ToList();

            TimeSpan IntersectLen((DateTime S, DateTime E, EventType T) e)
            {
                var s = e.S < arrival ? arrival : e.S;
                var ee = e.E > departure ? departure : e.E;
                return ee > s ? (ee - s) : TimeSpan.Zero;
            }

            var eight = TimeSpan.FromHours(8);
            var gross = departure - arrival;
            var lunchDur = lunchEnd > lunchStart ? (lunchEnd - lunchStart) : TimeSpan.Zero;

            bool fullSpecialDay =
                specials.Any(sp => sp.T == EventType.Vacation && IntersectLen(sp) >= eight) ||
                specials.Any(sp => sp.T != EventType.Vacation && IntersectLen(sp) >= (gross - lunchDur));

            if (fullSpecialDay)
            {
                foreach (var e in _eventService.GetEventsForDay(day)
                             .Where(e => e.EventType == EventType.Lunch && !e.IsAutoGenerated)
                             .ToList())
                    _eventService.DeleteEvent(e.Id);
                SaveUserSettingsFromEvents(day);
                return;
            }

            var overlapping = manual
            .Where(l => Overlaps(lunchStart.TimeOfDay, lunchEnd.TimeOfDay, l.S.TimeOfDay, l.E.TimeOfDay))
            .ToList();
            bool lunchCollision = overlapping.Any();

            if (lunchCollision)
            {
                if (!_moveAllLunchesForAllDays.HasValue)
                    _moveAllLunchesForAllDays = await _askCollision($"Oběd {lunchStart:HH\\:mm}-{lunchEnd:HH\\:mm} se překrývá s události. Přesunout všechny obědy s kolizemi hned?");
                if (_moveAllLunchesForAllDays.Value)
                {
                    var lastEnd = overlapping.Max(l => l.E.TimeOfDay);
                    var duration = lunchEnd - lunchStart;
                    lunchStart = day + lastEnd;
                    lunchEnd = lunchStart + duration;
                }
                else
                {
                    var lunchTime = lunchEnd - lunchStart;
                    foreach (var m in overlapping)
                    {
                        var ok = await _askCollision($"Oběd {lunchStart:HH\\:mm}-{lunchEnd:HH\\:mm} se překrývá s událostí “{m.Event.Title}” dne {m.S:dd.MM.yyyy} ({m.S:HH\\:mm}-{m.E:HH\\:mm}). Přesunout oběd hned po této události?");
                        if (!ok) continue;
                        lunchStart = day + m.E.TimeOfDay;
                        lunchEnd = lunchStart + lunchTime;
                    }
                }
            }

            var std = lunchEnd - lunchStart;
            while (manual.Where(m => m.Event.EventType != EventType.Lunch).Any(m => Overlaps(lunchStart.TimeOfDay, lunchEnd.TimeOfDay, m.S.TimeOfDay, m.E.TimeOfDay)))
            {
                var lastEnd = manual.Where(m => m.Event.EventType != EventType.Lunch)
                                    .Where(m => Overlaps(lunchStart.TimeOfDay, lunchEnd.TimeOfDay, m.S.TimeOfDay, m.E.TimeOfDay))
                                    .Max(m => m.E.TimeOfDay);

                lunchStart = day + lastEnd;
                lunchEnd = lunchStart + std;
                if (lunchEnd > departure) break;
            }
            if (lunchStart < arrival) lunchStart = arrival;
            if (lunchEnd > departure) lunchEnd = departure;
            overlapsManual = manual
            .Where(l => l.Event.EventType != EventType.Lunch)
            .Any(l => Overlaps(lunchStart.TimeOfDay, lunchEnd.TimeOfDay, l.S.TimeOfDay, l.E.TimeOfDay));

            hasValidLunch =
                lunchEnd > lunchStart &&
                (lunchEnd - lunchStart) >= TimeSpan.FromMinutes(5) &&
                !overlapsManual &&
                !specials.Any(sp => Overlaps(lunchStart.TimeOfDay, lunchEnd.TimeOfDay, sp.S.TimeOfDay, sp.E.TimeOfDay));


            var newEvents = new List<Event>();

            if (canCreateAutoLunch && hasValidLunch)
            {
                newEvents.Add(new Event
                {
                    Title = global.AutoEventNameLunch,
                    StartTime = lunchStart,
                    EndTime = lunchEnd,
                    EventType = EventType.Lunch,
                    IsAutoGenerated = true,
                    AutoGeneratedForDate = day,
                    HasCollision = lunchCollision
                });
            }

            var busyCandidates = new List<(DateTime Start, DateTime End)>();
            busyCandidates.AddRange(manual.Select(l => (l.S, l.E)));
            busyCandidates.AddRange(specials.Select(s => (s.S, s.E)));
            if (newEvents.Any(e => e.EventType == EventType.Lunch))
            {
                var ln = newEvents.First(e => e.EventType == EventType.Lunch);
                busyCandidates.Add((ln.StartTime, ln.EndTime));
            }
            var busy = MergeIntervals(busyCandidates);

            var gaps = new List<(DateTime s, DateTime e)>();
            var cursor = arrival;
            foreach (var b in busy)
            {
                if (cursor >= departure) break;
                var gapEnd = Min(b.start, departure);
                if (gapEnd > cursor) gaps.Add((cursor, gapEnd));
                cursor = Max(cursor, b.end);
            }
            if (cursor < departure) gaps.Add((cursor, departure));

            foreach (var (s, e) in gaps)
            {
                if ((e - s) <= TimeSpan.FromMinutes(1)) continue;
                newEvents.Add(new Event
                {
                    Title = (newEvents.Any(x => x.EventType == EventType.Lunch) &&
                             s >= newEvents.First(x => x.EventType == EventType.Lunch).EndTime)
                             ? global.AutoEventNamePostLunch
                             : global.AutoEventNamePreLunch,
                    StartTime = s,
                    EndTime = e,
                    EventType = EventType.Work,
                    IsAutoGenerated = true,
                    AutoGeneratedForDate = day
                });
            }

            foreach (var ev in newEvents.Where(e => e.EventType == EventType.Work))
                ev.Title = (newEvents.Any(x => x.EventType == EventType.Lunch) && ev.StartTime >= newEvents.First(x => x.EventType == EventType.Lunch).EndTime)
                    ? global.AutoEventNamePostLunch
                    : global.AutoEventNamePreLunch;

            foreach (var ev in newEvents.Where(x => (x.EndTime - x.StartTime) > TimeSpan.FromMinutes(1)))
                _eventService.CreateAutoEvent(ev);
            var dm0 = calc.DailyMetrics(day, _eventService.GetEventsForDay(day));
            var net0 = dm0.workInclBT;
            if (!preserveUserSettings && net0 <= 12.0 - 1e-6)
            {
                var over0 = Math.Max(0, (dm0.specialNonPc + dm0.workInclBT) - 8.0);
                if (over0 > 1e-6)
                {
                    await _eventService.TrimOvertimeByAutoBlocksAsync(day, preserveUserSettings);
                }
            }
            var dayEvents = _eventService.GetEventsForDay(day)
                             .OrderBy(e => e.StartTime)
                             .ToList();

            var all = _eventService.GetEventsForDay(day);
            var dailyMetric = calc.DailyMetrics(day, all);
            var over = Math.Max(0, (dailyMetric.specialNonPc + dailyMetric.workInclBT) - 8.0);
            if (over > 1e-6 && !preserveUserSettings)
            {
                await _eventService.TrimOvertimeByAutoBlocksAsync(day, preserveUserSettings);
                return;
            }
            var dm = calc.DailyMetrics(day, dayEvents);
            var netWork = dm.workInclBT;

            if (netWork > 12.0 - 1e-6)
            {
                var candidates = dayEvents
                    .Where(e => e.EventType == EventType.Work && e.IsAutoGenerated && (e.EndTime - e.StartTime) >= TimeSpan.FromMinutes(40))
                    .OrderByDescending(e => (e.EndTime - e.StartTime)) 
                    .ToList();

                if (candidates.Any())
                {
                    var lunchLen = TimeSpan.FromMinutes(30);

                   
                    var mid = candidates.FirstOrDefault(e =>
                    {
                        var leftRoom = (e.EndTime - e.StartTime) - lunchLen;
                        return leftRoom >= TimeSpan.FromMinutes(1);
                    });

                    if (mid != null)
                    {
                        var L = mid.StartTime;
                        var R = mid.EndTime;

                        var margin = TimeSpan.FromMinutes(1);
                        var innerSpan = (R - L) - 2 * margin;

                        if (innerSpan >= lunchLen)
                        {
                            var cutStart = L + margin + (innerSpan - lunchLen) / 2;
                            var cutEnd = cutStart + lunchLen;

                            using (var db = new AppDbContext())
                            {
                                var a = db.Events.Single(x => x.Id == mid.Id && !x.IsDeleted);
                                a.EndTime = cutStart;
                                db.SaveChanges();
                            }

                            _eventService.CreateAutoEvent(new Event
                            {
                                Title = mid.Title,
                                EventType = EventType.Work,
                                StartTime = cutEnd,
                                EndTime = R,
                                IsAutoGenerated = true,
                                AutoGeneratedForDate = day
                            });

                            _eventService.CreateAutoEvent(new Event
                            {
                                Title = "Oběd (auto #2)",
                                EventType = EventType.Lunch,
                                StartTime = cutStart,
                                EndTime = cutEnd,
                                IsAutoGenerated = true,
                                AutoGeneratedForDate = day
                            });
                        }
                    }
                }
            }
            if (!preserveUserSettings)
              SaveUserSettingsFromEvents(day);
        }





        private void SaveUserSettingsFromEvents(DateTime day)
        {
            var evs = _eventService.GetEventsForDay(day).Where(e => !e.IsDeleted).OrderBy(e => e.StartTime).ToList();
            var sem = GetSemesterForDate(day);
            var global = GlobalSettingsService.LoadGlobalSettings(day.Year, sem) ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(global, day.DayOfWeek);

            var prev = SettingsService.GetUserSettingsForDate(day);

            // works = evs.Where(e => e.EventType is EventType.Work or EventType.BusinessTrip).ToList();
            const double EPS = 1e-6;
            var movedOut = WorkTransferReportingService.GetMovedOut(day);
            if (movedOut > EPS && prev != null)
            {
                var ar = prev.ArrivalTime;
                var de = prev.DepartureTime;

                TimeSpan lS = TimeSpan.Zero, lE = TimeSpan.Zero;
                var lunch = evs.FirstOrDefault(e => e.EventType == EventType.Lunch);
                if (lunch != null)
                {
                    var tls = lunch.StartTime.TimeOfDay;
                    var tle = lunch.EndTime.TimeOfDay;
                    if (tle > tls && tls >= ar && tle <= de) { lS = tls; lE = tle; }
                }

                SettingsService.SaveUserSettingsForDate(day, ar, de, lS, lE);
                return;
            }
            TimeSpan arr = prev?.ArrivalTime ?? defArr;
            TimeSpan dep = prev?.DepartureTime ?? defDep;
            if (evs.Any())
            {
                arr = evs.Min(e => e.StartTime).TimeOfDay;
                dep = evs.Max(e => e.EndTime).TimeOfDay;
            }
            if (dep < arr) dep = arr;

            bool isFullSpecialDay()
            {
                
                var specials = evs.Where(e => e.EventType != EventType.Work && e.EventType != EventType.Lunch).ToList();
                if (specials.Count == 0) return false;

                var dayStart = day + arr;
                var dayEnd = day + dep;
                TimeSpan eight = TimeSpan.FromHours(8);

                foreach (var s in specials)
                {
                    var sClipS = s.StartTime < (day + arr) ? (day + arr) : s.StartTime;
                    var sClipE = s.EndTime > (day + dep) ? (day + dep) : s.EndTime;
                    var len = (sClipE > sClipS) ? (sClipE - sClipS) : TimeSpan.Zero;

                    if (s.EventType == EventType.Vacation && len >= eight)
                        return true;
                    if (len >= (dayEnd - dayStart))
                        return true;
                }
                return false;
            }

           
            TimeSpan ls = TimeSpan.Zero, le = TimeSpan.Zero;
            if (isFullSpecialDay())
            {
                ls = le = TimeSpan.Zero;
            }
            else
            {
                var lunchEv = evs.FirstOrDefault(e => e.EventType == EventType.Lunch);
                if (lunchEv != null)
                {
                    var tls = lunchEv.StartTime.TimeOfDay;
                    var tle = lunchEv.EndTime.TimeOfDay;
                    if (tle > tls && tls >= arr && tle <= dep)
                    {
                        (ls, le) = (tls, tle);
                    }
                }

                if (le <= ls && prev is not null && prev.LunchEnd > prev.LunchStart)
                {
                    if (prev.LunchStart >= arr && prev.LunchEnd <= dep)
                        (ls, le) = (prev.LunchStart, prev.LunchEnd);
                    else
                    {
                        
                        var want = prev.LunchEnd - prev.LunchStart;
                        var candLs = (prev.LunchStart < arr) ? arr : prev.LunchStart;
                        var candLe = candLs + want;
                        if (want > TimeSpan.Zero && candLe <= dep)
                            (ls, le) = (candLs, candLe);
                    }
                }

                if (le <= ls && defLe > defLs && defLs >= arr && defLe <= dep)
                    (ls, le) = (defLs, defLe);
            }

            SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
        }


        private static bool Overlaps(TimeSpan a0, TimeSpan a1, TimeSpan b0, TimeSpan b1)
            => a0 < b1 && b0 < a1;

        private (TimeSpan arr, TimeSpan dep, TimeSpan lunchStart, TimeSpan lunchEnd)
        GetDaySpans(GlobalSettings g, UserSettings u, DayOfWeek wd)
        {
            string sa, sd, s0, s1;
            switch (wd)
            {
                case DayOfWeek.Monday:
                    (sa, sd, s0, s1) =
                      (g.MondayArrival, g.MondayDeparture,
                       g.MondayLunchStart, g.MondayLunchEnd);
                    break;
                case DayOfWeek.Tuesday:
                    (sa, sd, s0, s1) =
                      (g.TuesdayArrival, g.TuesdayDeparture,
                       g.TuesdayLunchStart, g.TuesdayLunchEnd);
                    break;
                case DayOfWeek.Wednesday:
                    (sa, sd, s0, s1) =
                      (g.WednesdayArrival, g.WednesdayDeparture,
                       g.WednesdayLunchStart, g.WednesdayLunchEnd);
                    break;
                case DayOfWeek.Thursday:
                    (sa, sd, s0, s1) =
                      (g.ThursdayArrival, g.ThursdayDeparture,
                       g.ThursdayLunchStart, g.ThursdayLunchEnd);
                    break;
                case DayOfWeek.Friday:
                    (sa, sd, s0, s1) =
                      (g.FridayArrival, g.FridayDeparture,
                       g.FridayLunchStart, g.FridayLunchEnd);
                    break;
                default:
                    throw new InvalidOperationException("Není pracovný den");
            }

            if (u != null)
            {
                sa = u.ArrivalTime.ToString(@"hh\:mm");
                sd = u.DepartureTime.ToString(@"hh\:mm");
                s0 = u.LunchStart.ToString(@"hh\:mm");
                s1 = u.LunchEnd.ToString(@"hh\:mm");
            }
            if (string.IsNullOrWhiteSpace(sa) || string.IsNullOrWhiteSpace(sd))
            {
                sa = g.GlobalStartTime;
                sd = g.GlobalEndTime;
            }

            var arr = TimeSpan.Parse(sa, CultureInfo.InvariantCulture);
            var dep = TimeSpan.Parse(sd, CultureInfo.InvariantCulture);


            TimeSpan lunchStart, lunchEnd;
            if (string.IsNullOrWhiteSpace(s0) || string.IsNullOrWhiteSpace(s1))
            {
                var halfSpan = (dep - arr) / 2;
                lunchStart = arr + halfSpan - TimeSpan.FromMinutes(15);
                lunchEnd = lunchStart + TimeSpan.FromMinutes(30);
            }
            else
            {
                lunchStart = TimeSpan.Parse(s0, CultureInfo.InvariantCulture);
                lunchEnd = TimeSpan.Parse(s1, CultureInfo.InvariantCulture);
            }


            return (arr, dep, lunchStart, lunchEnd);
        }
        static DateTime Min(DateTime a, DateTime b) => a < b ? a : b;
        static DateTime Max(DateTime a, DateTime b) => a > b ? a : b;

        public async Task RegenerateRangeEventsAsync(DateTime start, DateTime end, bool preserveUserSettings = false)
        {
            _moveAllLunchesForAllDays = null;
            for (var d = start.Date; d <= end.Date; d = d.AddDays(1))
                await RegenerateDailyEventsAsync(d, preserveUserSettings);

            MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
        }
        private bool IsInVacation(DateTime day, out GlobalSettings global)
        {
            var sem = GetSemesterForDate(day);
            global = GlobalSettingsService
                        .LoadGlobalSettings(day.Year,sem)
                     ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);

            int md = day.Month * 100 + day.Day;

            int winterStart = 12 * 100 + 23;
            int winterEnd = 1 * 100 + 1;
            bool inWinter = (md >= winterStart) || (md <= winterEnd);

            int summerStart = 6 * 100 + 30;
            int summerEnd = 8 * 100 + 10;
            bool inSummer = md >= summerStart && md <= summerEnd;

            return inWinter || inSummer;
        }
        private List<(DateTime start, DateTime end)> MergeIntervals(List<(DateTime start, DateTime end)> intervals)
        {
            var sorted = intervals.OrderBy(x => x.start).ToList();
            var merged = new List<(DateTime start, DateTime end)>();
            foreach (var seg in sorted)
            {
                if (merged.Count == 0 || merged[^1].end < seg.start)
                    merged.Add(seg);
                else
                    merged[^1] = (
                        merged[^1].start,
                        merged[^1].end > seg.end ? merged[^1].end : seg.end
                    );
            }
            return merged;
        }
        private static double OverlapHours(DateTime segStart, DateTime segEnd,
                                   List<(DateTime start, DateTime end)> intervals)
        {
            double sum = 0;
            foreach (var iv in intervals)
            {
                var s = segStart > iv.start ? segStart : iv.start;
                var e = segEnd < iv.end ? segEnd : iv.end;
                if (e > s) sum += (e - s).TotalHours;
            }
            return sum;
        }
    }
}
