using Microsoft.EntityFrameworkCore;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TeacherScheduleApp.Data;
using TeacherScheduleApp.Helpers;
using TeacherScheduleApp.Messages;
using TeacherScheduleApp.Models;

namespace TeacherScheduleApp.Services
{
    class MoveLunchState { public bool? State; }
    public class EventService
    {
        string H(DateTime dt) => dt.ToString("HH\\:mm");
        public EventService()
        {
            Log.Init();
            Log.Info("EventService created");
        }
        private static List<(DateTime s, DateTime e, List<Event> owners)>BuildMergedWithOwners(IEnumerable<Event> evs, DateTime winS, DateTime winE)
        {
            var segs = evs
                .Select(e => (
                    s: e.StartTime < winS ? winS : e.StartTime,
                    e: e.EndTime > winE ? winE : e.EndTime,
                    ev: e))
                .Where(x => x.e > x.s)
                .OrderBy(x => x.s)
                .ToList();

            var merged = new List<(DateTime s, DateTime e, List<Event> owners)>();
            foreach (var seg in segs)
            {
                if (merged.Count == 0 || merged[^1].e < seg.s)
                    merged.Add((seg.s, seg.e, new List<Event> { seg.ev }));
                else
                {
                    if (seg.e > merged[^1].e) merged[^1] = (merged[^1].s, seg.e, merged[^1].owners);
                    merged[^1].owners.Add(seg.ev);
                }
            }
            return merged;
        }
        public void CreateEvent(Event ev)
        {
            if (ev.IsAutoGenerated)
            {
                using var dbContext = new AppDbContext();
                dbContext.Events.Add(ev);
                dbContext.SaveChanges();
                return;
            }
            DateTime parentDate = ev.StartTime.Date;
            while (parentDate <= ev.EndTime.Date && (parentDate.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday || HolidayHelper.IsCzechHoliday(parentDate)))
            {
                parentDate = parentDate.AddDays(1);
            }
            if (parentDate > ev.EndTime.Date)
                return;

            using var db = new AppDbContext();

            var parent = new Event
            {
                Title = ev.Title,
                Description = ev.Description,
                EventType = ev.EventType,
                AllDay = ev.AllDay,
                StartTime = parentDate + ev.StartTime.TimeOfDay,
                EndTime = parentDate + ev.EndTime.TimeOfDay,
                ArrivalTime = parentDate + ev.ArrivalTime.TimeOfDay,
                DepartureTime = parentDate + ev.DepartureTime.TimeOfDay,
                LunchStart = parentDate + ev.LunchStart.TimeOfDay,
                LunchEnd = parentDate + ev.LunchEnd.TimeOfDay,
                ParentEventId = null,
                IsAutoGenerated = ev.IsAutoGenerated,
                ImportBatchId = ev.ImportBatchId,
                ImportLabel = ev.ImportLabel

            };
            db.Events.Add(parent);
            db.SaveChanges();

            for (var day = parentDate.AddDays(1); day <= ev.EndTime.Date; day = day.AddDays(1))
            {
                if (day.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday || HolidayHelper.IsCzechHoliday(day))
                    continue;

                var child = new Event
                {
                    Title = ev.Title,
                    Description = ev.Description,
                    EventType = ev.EventType,
                    AllDay = ev.AllDay,
                    StartTime = day + ev.StartTime.TimeOfDay,
                    EndTime = day + ev.EndTime.TimeOfDay,
                    ArrivalTime = day + ev.ArrivalTime.TimeOfDay,
                    DepartureTime = day + ev.DepartureTime.TimeOfDay,
                    LunchStart = day + ev.LunchStart.TimeOfDay,
                    LunchEnd = day + ev.LunchEnd.TimeOfDay,
                    ParentEventId = parent.Id,
                    IsAutoGenerated = ev.IsAutoGenerated,
                    ImportBatchId = ev.ImportBatchId,
                    ImportLabel = ev.ImportLabel
                };
                db.Events.Add(child);
            }
            db.SaveChanges();

            var affectedDates = Enumerable
                .Range(0, (ev.EndTime.Date - parentDate).Days + 1)
                .Select(offset => parentDate.AddDays(offset))
                .Where(d => d.DayOfWeek is not DayOfWeek.Saturday and not DayOfWeek.Sunday
                         && !HolidayHelper.IsCzechHoliday(d))
                .ToList();

            var autos = db.Events
                .Where(x => x.IsAutoGenerated
                         && x.AutoGeneratedForDate.HasValue
                         && affectedDates.Contains(x.AutoGeneratedForDate.Value.Date))
                .ToList();
            db.Events.RemoveRange(autos);
            db.SaveChanges();

            var sem = GlobalSettingsService.GetSemesterForDate(parentDate);
            var glob = GlobalSettingsService.LoadGlobalSettings(parentDate.Year, sem)
                        ?? GlobalSettingsService.GetDefaultSettings(parentDate.Year, sem);
            var gStart = TimeSpan.Parse(glob.GlobalStartTime);
            var gEnd = TimeSpan.Parse(glob.GlobalEndTime);
            var norm = gEnd - gStart;

            var manualSpan = ev.AllDay ? norm : (ev.EndTime.TimeOfDay - ev.StartTime.TimeOfDay);

         
            var autoGen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false)
            );
            foreach (var d in affectedDates)
            {
                autoGen.RegenerateDailyEventsAsync(d).Wait();
            }
        }

        public List<Event> GetAllEvents()
        {
            using var db = new AppDbContext();
            return db.Events.ToList();
        }

        public List<Event> LoadEvents()
        {
            using (var context = new AppDbContext())
            {
                return context.Events
                              .Where(e => !e.IsDeleted)
                              .ToList();
            }
        }

        public Event GetEventById(int id)
        {
            using var db = new AppDbContext();
            return db.Events.Find(id);
        }

        public void UpdateEvent(Event ev, bool suppressRegen = false)
        {
            using var db = new AppDbContext();
            var parent = db.Events.SingleOrDefault(x => x.Id == ev.Id);
            if (parent == null)
                return;

            var oldEndDate = parent.EndTime.Date;
            parent.Title = ev.Title;
            parent.StartTime = ev.StartTime;
            parent.EndTime = ev.EndTime;
            parent.AllDay = ev.AllDay;
            parent.Description = ev.Description;
            parent.IsDeleted = ev.IsDeleted;
            parent.EventType = ev.EventType;
            parent.ArrivalTime = ev.ArrivalTime;
            parent.DepartureTime = ev.DepartureTime;
            parent.LunchStart = ev.LunchStart;
            parent.LunchEnd = ev.LunchEnd;
            parent.IsAutoGenerated = ev.IsAutoGenerated;
            parent.HasCollision = ev.HasCollision;
            parent.AutoGeneratedForDate = ev.AutoGeneratedForDate;
            db.SaveChanges();

            var oldChildren = db.Events.Where(c => c.ParentEventId == parent.Id).ToList();
            if (oldChildren.Any())
            {
                db.Events.RemoveRange(oldChildren);
                db.SaveChanges();
            }

            DateTime start = parent.StartTime.Date.AddDays(1);
            for (var day = start; day <= ev.EndTime.Date; day = day.AddDays(1))
            {
                if (day.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday
                 || HolidayHelper.IsCzechHoliday(day))
                    continue;

                var child = new Event
                {
                    Title = parent.Title,
                    Description = parent.Description,
                    EventType = parent.EventType,
                    AllDay = parent.AllDay,
                    StartTime = day + parent.StartTime.TimeOfDay,
                    EndTime = day + parent.EndTime.TimeOfDay,
                    ArrivalTime = day + parent.ArrivalTime.TimeOfDay,
                    DepartureTime = day + parent.DepartureTime.TimeOfDay,
                    LunchStart = day + parent.LunchStart.TimeOfDay,
                    LunchEnd = day + parent.LunchEnd.TimeOfDay,
                    ParentEventId = parent.Id,
                    IsAutoGenerated = parent.IsAutoGenerated
                };
                db.Events.Add(child);
            }
            db.SaveChanges();
            if (!suppressRegen)
            {
                var dayToRegen = parent.StartTime.Date;
                var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
                gen.RegenerateDailyEventsAsync(dayToRegen).GetAwaiter().GetResult();
                MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
                MessageBus.Current.SendMessage(new UserSettingsChangedMessage(dayToRegen));
            }
        }

        public void DeleteEvent(int id)
        {
            using var db = new AppDbContext();
            var ev = db.Events.FirstOrDefault(e => e.Id == id);
            if (ev == null) return;

            var day = ev.StartTime.Date;

            ev.IsDeleted = true;
            db.SaveChanges();

            AdjustUserSettingsAfterDeletion(day);

            var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
            gen.RegenerateDailyEventsAsync(day).GetAwaiter().GetResult();

            MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
            MessageBus.Current.SendMessage(new UserSettingsChangedMessage(day));
        }

        public List<Event> GetEventsForDay(DateTime date)
        {
            using var db = new AppDbContext();
            return db.Events
                     .Where(e => e.StartTime.Date == date.Date && !e.IsDeleted)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }

        public List<Event> GetEventsForWeek(DateTime anyDate)
        {
            var date = anyDate.Date;
            int delta = (int)date.DayOfWeek - (int)DayOfWeek.Monday;
            if (delta < 0) delta += 7;
            var weekStart = date.AddDays(-delta);

            var weekEnd = weekStart.AddDays(7);


            using var db = new AppDbContext();
            return db.Events
                     .Where(e =>
                         !e.IsDeleted &&
                         e.StartTime < weekEnd &&
                         e.EndTime >= weekStart)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }


        public List<Event> GetEventsForMonth(DateTime date)
        {
            using var db = new AppDbContext();
            var year = date.Year;
            var month = date.Month;
            return db.Events
                     .Where(e =>
                         e.StartTime.Year == year &&
                         e.StartTime.Month == month &&
                         !e.IsDeleted)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }
        public List<Event> GetEventsForRange(DateTime start, DateTime end)
        {
            using var db = new AppDbContext();
            return db.Events
                     .Where(e => e.StartTime < end && e.EndTime >= start && !e.IsDeleted)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }
        public Event? FindEventByStartTime(DateTime startTime)
        {
            using var db = new AppDbContext();
            return db.Events.FirstOrDefault(e => e.StartTime == startTime && !e.IsDeleted);
        }

        public void CreateAutoEvent(Event ev)
        {
            using var db = new AppDbContext();
            db.Events.Add(ev);
            db.SaveChanges();
        }

        public void RemoveAutoGeneratedEvents(DateTime date)
        {
            using var db = new AppDbContext();
            var evs = db.Events
                .Where(e => e.IsAutoGenerated && e.AutoGeneratedForDate == date.Date)
                .ToList();
            foreach (var e in evs)
                db.Events.Remove(e);
            db.SaveChanges();
        }

        public async Task BalanceEventsForMonthAsync(int year, int month, Func<string, Task<bool>> askCollision)
        {
            Log.Info($"Balance START for {month:D2}-{year:D4}");
            if (month < 1 || month > 12)
            {
                var normalized = new DateTime(year, 1, 1).AddMonths(month - 1);
                year = normalized.Year;
                month = normalized.Month;
            }
            var first = new DateTime(year, month, 1);
            var last = new DateTime(year, month, DateTime.DaysInMonth(year, month));
            var days = Enumerable.Range(0, (last - first).Days + 1)
                .Select(i => first.AddDays(i))
                .Where(d => d.DayOfWeek is not DayOfWeek.Saturday and not DayOfWeek.Sunday && !HolidayHelper.IsCzechHoliday(d))
                .ToList();
            Log.Debug($"Workdays: {string.Join(", ", days.Select(d => d.ToString("dd.MM")))}");
            var calc = new WorkingHoursCalculatorService();

            static List<(DateTime s, DateTime e)> MergeIv(IEnumerable<(DateTime s, DateTime e)> iv)
            {
                var list = iv.Where(x => x.e > x.s).OrderBy(x => x.s).ToList();
                var res = new List<(DateTime s, DateTime e)>();
                foreach (var seg in list)
                {
                    if (res.Count == 0 || res[^1].e < seg.s) res.Add(seg);
                    else res[^1] = (res[^1].s, res[^1].e > seg.e ? res[^1].e : seg.e);
                }
                return res;
            }

            (TimeSpan arr, TimeSpan dep, TimeSpan ls, TimeSpan le) GetWindow(DateTime day)
            {
                var sem = GlobalSettingsService.GetSemesterForDate(day);
                var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                          ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
                var def = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);
                var us = SettingsService.GetUserSettingsForDate(day);
                return us is null ? def : (us.ArrivalTime, us.DepartureTime, us.LunchStart, us.LunchEnd);
            }

            List<(DateTime s, DateTime e)> FreeGaps(DateTime day)
            {
                var (arr, dep, _, _) = GetWindow(day);
                var winS = day + arr; var winE = day + dep;
                var evs = GetEventsForDay(day);
                var busy = evs.Where(e => e.EventType != EventType.Lunch)
                              .Select(e => (s: e.StartTime < winS ? winS : e.StartTime,
                                            e: e.EndTime > winE ? winE : e.EndTime))
                              .Where(x => x.e > x.s);
                var merged = MergeIv(busy);
                var gaps = new List<(DateTime s, DateTime e)>();
                var cur = winS;
                foreach (var b in merged)
                {
                    if (b.s > cur) gaps.Add((cur, b.s));
                    if (b.e > cur) cur = b.e;
                }
                if (cur < winE) gaps.Add((cur, winE));
                return gaps;
            }
            async Task<bool> ConfirmMoveAsync(DateTime fromDay, DateTime toDay, double hours)
            {
                var donorWork = GetEventsForDay(fromDay)
                    .Where(e => (e.EventType == EventType.Work || e.EventType == EventType.BusinessTrip) && !e.IsDeleted)
                    .OrderByDescending(e => e.EndTime)
                    .FirstOrDefault();

                string donorInfo = donorWork != null
                    ? $"- {donorWork.Title} ({H(donorWork.StartTime)}–{H(donorWork.EndTime)})"
                    : "- žádná pracovní událost nenalezena";

                var msg =
                    $"Chystáte se přesunout {hours:0.##} h " +
                    $"z dne {fromDay:dd.MM.yyyy} do dne {toDay:dd.MM.yyyy}.\n\n" +
                    $"U **dárce** bude zkrácena poslední pracovní událost:\n{donorInfo}\n\n" +
                    $"V **příjemci** bude vložen automatický blok práce do nejbližší volné mezery " +
                    $"(případně se posune zač./konec dne).\n\n" +
                    $"Pokračovat?";

                Log.Debug($"ConfirmMove: {hours:0.##}h from {fromDay:dd.MM} to {toDay:dd.MM}. Donor='{donorWork?.Title}' {donorWork?.StartTime:HH:mm}-{donorWork?.EndTime:HH:mm}");
                var res = await askCollision(msg);
                Log.Info($"ConfirmMove result: {(res ? "YES" : "NO")}");
                return res;
            }
            async Task RebuildDay(DateTime day)
            {
                Log.Debug($"RebuildDay start {day:dd.MM}");
                try
                {
                    var gen = new AutomaticEventsGeneratorService(this, askCollision);
                    await gen.RegenerateDailyEventsAsync(day);
                    MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
                    MessageBus.Current.SendMessage(new UserSettingsChangedMessage(day));
                    Log.Debug($"RebuildDay done {day:dd.MM}");
                }
                catch (Exception ex)
                {
                    Log.Error($"RebuildDay error {day:dd.MM}: {ex}");
                    throw;
                }
            }

            async Task<double> CutFromDonor(DateTime day, double maxNeed)
            {
                Log.Debug($"CutFromDonor enter: day={day:dd.MM}, maxNeed={maxNeed:0.##}");
                if (maxNeed <= 1e-6) return 0;

                var all = GetEventsForDay(day);
                var dm = calc.DailyMetrics(day, all);

                var canGive = Math.Max(0, (dm.specialNonPc + dm.workInclBT) - 8.0);
                Log.Debug($"Day {day:dd.MM}: canGive={canGive:0.###}");

                if (canGive <= 1e-6) return 0;
                var taken = await TrimDonorFromEndByUnionAsync(day, Math.Min(canGive, maxNeed));
                if (taken > 1e-6) return taken;
                var toCut = Math.Min(canGive, maxNeed);

                var (arr, dep, ls, le) = GetWindow(day);

                var lastWork = all.Where(e => (e.EventType == EventType.Work || e.EventType == EventType.BusinessTrip) && !e.IsDeleted).OrderByDescending(e => e.EndTime).FirstOrDefault();
                if (lastWork != null)
                    Log.Debug($"Try trim last block: '{lastWork.Title}' {lastWork.StartTime:HH:mm}-{lastWork.EndTime:HH:mm}");

                if (lastWork != null)
                {
                    var maxCutFromBlock = Math.Max(0, (lastWork.EndTime - lastWork.StartTime).TotalHours);
                    var realCut = Math.Min(toCut, maxCutFromBlock);

                    if (realCut > 1e-6)
                    {
                        var cutTs = TimeSpan.FromHours(realCut);
                        var newEnd = lastWork.EndTime - cutTs;
                        Log.Info($"Trimmed {realCut:0.##}h from {day:dd.MM} block -> newEnd={newEnd:HH:mm}");

                        if (newEnd < lastWork.StartTime) newEnd = lastWork.StartTime;

                        lastWork.EndTime = newEnd;
                        UpdateSingleEventEnd(lastWork.Id, newEnd);

                        var us = SettingsService.GetUserSettingsForDate(day);
                        var curArr = us?.ArrivalTime ?? arr;
                        var curDep = us?.DepartureTime ?? dep;
                        var lastManualEndAfterTrim = GetEventsForDay(day)
                        .Where(e => !e.IsAutoGenerated && e.EventType != EventType.Lunch)
                        .Select(e => e.EndTime)
                        .DefaultIfEmpty(day + curArr)
                        .Max()
                        .TimeOfDay;

                        var newDepT = curDep > lastManualEndAfterTrim ? lastManualEndAfterTrim : curDep;

                        var newLs = us?.LunchStart ?? ls;
                        var newLe = us?.LunchEnd ?? le;
                        if (newLe > newLs && (newLe > newDepT || newLs < curArr))
                            (newLs, newLe) = (TimeSpan.Zero, TimeSpan.Zero);

                        SettingsService.SaveUserSettingsForDate(day, curArr, newDepT, newLs, newLe);
                        var us2 = SettingsService.GetUserSettingsForDate(day);
                        ReplaceLunchEvent(day, us2?.LunchStart ?? TimeSpan.Zero, us2?.LunchEnd ?? TimeSpan.Zero);
                        await RebuildDay(day);
                        return realCut;
                    }
                }

                var lastManualEnd = all
                    .Where(e => !e.IsAutoGenerated && e.EventType != EventType.Lunch)
                    .Select(e => e.EndTime)
                    .DefaultIfEmpty(day + arr)
                    .Max();

                var maxCutByWindow = (dep - lastManualEnd.TimeOfDay).TotalHours;
                var realCutByDep = Math.Max(0, Math.Min(toCut, maxCutByWindow));
                if (realCutByDep <= 1e-6) return 0;

                var newDep2 = dep - TimeSpan.FromHours(realCutByDep);
                Log.Debug($"Fallback by dep: lastManualEnd={lastManualEnd:HH:mm}, dep={dep}, maxCutByWindow={maxCutByWindow:0.##}, realCutByDep={realCutByDep:0.##}");
                Log.Info($"Cut by dep {realCutByDep:0.##}h on {day:dd.MM}, newDep={newDep2}");

                TimeSpan newLs2 = ls, newLe2 = le;
                if (newLe2 > newLs2 && (newLe2 > newDep2 || newLs2 < arr))
                    (newLs2, newLe2) = (TimeSpan.Zero, TimeSpan.Zero);

                SettingsService.SaveUserSettingsForDate(day, arr, newDep2, newLs2, newLe2);
                var us3 = SettingsService.GetUserSettingsForDate(day);
                ReplaceLunchEvent(day, us3?.LunchStart ?? TimeSpan.Zero, us3?.LunchEnd ?? TimeSpan.Zero);
                await RebuildDay(day);
                Log.Debug($"CutFromDonor exit: returned={realCutByDep:0.##}");
                return realCutByDep;
            }
            var lunchState = new MoveLunchState();
            async Task<double> PlaceToRecipient(DateTime day, double amount)
            {
                Log.Debug($"PlaceToRecipient enter: day={day:dd.MM}, amount={amount:0.##}");
                if (amount <= 1e-6) return 0;
                double placed = 0;
                var (arr, dep, ls, le) = GetWindow(day);

                DateTime lunchS = day + ls, lunchE = day + le;

                List<(DateTime s, DateTime e)> gaps()
                {
                    var (a, d, _, _) = GetWindow(day);
                    var winS = day + a; var winE = day + d;
                    var evs = GetEventsForDay(day);
                    var busy = evs.Where(e => e.EventType != EventType.Lunch).Select(e => (s: e.StartTime < winS ? winS : e.StartTime, e: e.EndTime > winE ? winE : e.EndTime))
                    .Where(x => x.e > x.s)
                    .OrderBy(x => x.s)
                    .ToList();

                    var merged = new List<(DateTime s, DateTime e)>();
                    foreach (var b in busy)
                    {
                        if (merged.Count == 0 || merged[^1].e < b.s) merged.Add(b);
                        else merged[^1] = (merged[^1].s, merged[^1].e > b.e ? merged[^1].e : b.e);
                    }

                    var gaps = new List<(DateTime s, DateTime e)>();
                    var cur = winS;
                    foreach (var b in merged)
                    {
                        if (b.s > cur) gaps.Add((cur, b.s));
                        if (b.e > cur) cur = b.e;
                    }
                    if (cur < winE) gaps.Add((cur, winE));
                    return gaps;
                }

                async Task ensureLunchOutside(DateTime segS, DateTime segE)
                {
                    bool overlaps = (le > ls) && !(segE <= lunchS || lunchE <= segS);
                    if (!overlaps) { Log.Debug("Lunch OK, no overlap."); return; }
                    Log.Warn($"Lunch overlap on {day:dd.MM} with {segS:HH:mm}-{segE:HH:mm}");
                    if (!lunchState.State.HasValue)
                        lunchState.State = await askCollision("Nový blok práce koliduje s obědem. Posunout oběd za blok pro všechny takové případy?");

                    if (lunchState.State!.Value)
                    {
                        var newLs = segE.TimeOfDay;
                        var newLe = newLs + (le - ls);

                        var newArr = SettingsService.GetUserSettingsForDate(day)?.ArrivalTime ?? arr;
                        var newDep = SettingsService.GetUserSettingsForDate(day)?.DepartureTime ?? dep;
                        Log.Info(lunchState.State!.Value
                        ? $"Lunch moved to after block: {newLs:hh\\:mm}-{newLe:hh\\:mm}"
                        : "Lunch removed for the day");
                        if (day + newLe > day + newDep)
                            SettingsService.SaveUserSettingsForDate(day, newArr, newDep, TimeSpan.Zero, TimeSpan.Zero);
                        else
                            SettingsService.SaveUserSettingsForDate(day, newArr, newDep, newLs, newLe);
                        var us2 = SettingsService.GetUserSettingsForDate(day);
                        ReplaceLunchEvent(day, us2?.LunchStart ?? TimeSpan.Zero, us2?.LunchEnd ?? TimeSpan.Zero);
                        var us = SettingsService.GetUserSettingsForDate(day);
                        lunchS = day + (us?.LunchStart ?? TimeSpan.Zero);
                        lunchE = day + (us?.LunchEnd ?? TimeSpan.Zero);
                    }
                    else
                    {
                        var newArr = SettingsService.GetUserSettingsForDate(day)?.ArrivalTime ?? arr;
                        var newDep = SettingsService.GetUserSettingsForDate(day)?.DepartureTime ?? dep;
                        SettingsService.SaveUserSettingsForDate(day, newArr, newDep, TimeSpan.Zero, TimeSpan.Zero);
                        var us2 = SettingsService.GetUserSettingsForDate(day);
                        ReplaceLunchEvent(day, us2?.LunchStart ?? TimeSpan.Zero, us2?.LunchEnd ?? TimeSpan.Zero);
                        lunchS = lunchE = day;
                    }
                }

                foreach (var g in gaps())
                {
                    Log.Debug($"Gap {day:dd.MM} {g.s:HH:mm}-{g.e:HH:mm} free={(g.e - g.s).TotalHours:0.##}h");
                    if (placed >= amount - 1e-6) break;
                    var free = (g.e - g.s).TotalHours;
                    if (free <= 1e-6) continue;

                    var take = Math.Min(free, amount - placed);
                    var segS = g.s;
                    var segE = g.s.AddHours(take);
                    Log.Info($"Place segment {take:0.##}h -> {segS:HH:mm}-{segE:HH:mm} (day {day:dd.MM})");
                    await ensureLunchOutside(segS, segE);

                    CreateAutoEvent(new Event
                    {
                        Title = "Vyvažování práce",
                        EventType = EventType.Work,
                        StartTime = segS,
                        EndTime = segE,
                        IsAutoGenerated = true,
                        AutoGeneratedForDate = day
                    });

                    placed += take;
                }

                if (placed >= amount - 1e-6)
                {
                    await RebuildDay(day);
                    return placed;
                }

                var still = amount - placed;

                var existing = GetEventsForDay(day).Where(e => e.EventType != EventType.Lunch).ToList();
                var lastBusyEnd = existing.Select(e => e.EndTime).DefaultIfEmpty(day + arr).Max();

                if (lastBusyEnd.TimeOfDay <= dep)
                {
                    var newDep = (lastBusyEnd + TimeSpan.FromHours(still)).TimeOfDay;
                    var curUs = SettingsService.GetUserSettingsForDate(day);
                    var newArr = curUs?.ArrivalTime ?? arr;
                    var curLs = curUs?.LunchStart ?? ls;
                    var curLe = curUs?.LunchEnd ?? le;

                    Log.Info($"Extend dep on {day:dd.MM} by {still:0.##}h -> newDep={newDep}");
                    Log.Info($"Extend arr on {day:dd.MM} by {-still:0.##}h -> newArr={newArr}");

                    SettingsService.SaveUserSettingsForDate(day, newArr, newDep, curLs, curLe);

                    var seg2S = lastBusyEnd;
                    var seg2E = lastBusyEnd.AddHours(still);

                    await ensureLunchOutside(seg2S, seg2E);

                    CreateAutoEvent(new Event
                    {
                        Title = "Vyvažování práce",
                        EventType = EventType.Work,
                        StartTime = seg2S,
                        EndTime = seg2E,
                        IsAutoGenerated = true,
                        AutoGeneratedForDate = day
                    });

                    placed += still;
                    await RebuildDay(day);
                    return placed;
                }

                var firstBusyStart = existing.Select(e => e.StartTime).DefaultIfEmpty(day + dep).Min();
                var curArr = SettingsService.GetUserSettingsForDate(day)?.ArrivalTime ?? arr;

                if ((firstBusyStart.TimeOfDay - curArr).TotalHours >= still)
                {
                    var seg3S = firstBusyStart.AddHours(-still);
                    var seg3E = firstBusyStart;

                    var curUs2 = SettingsService.GetUserSettingsForDate(day);
                    var newArr = seg3S.TimeOfDay;
                    var curDep = curUs2?.DepartureTime ?? dep;
                    var curLs2 = curUs2?.LunchStart ?? ls;
                    var curLe2 = curUs2?.LunchEnd ?? le;

                    SettingsService.SaveUserSettingsForDate(day, newArr, curDep, curLs2, curLe2);

                    await ensureLunchOutside(seg3S, seg3E);

                    CreateAutoEvent(new Event
                    {
                        Title = "Vyvažování práce",
                        EventType = EventType.Work,
                        StartTime = seg3S,
                        EndTime = seg3E,
                        IsAutoGenerated = true,
                        AutoGeneratedForDate = day
                    });

                    placed += still;
                    await RebuildDay(day);
                    return placed;
                }

                if (placed > 1e-6) await RebuildDay(day);
                Log.Debug($"PlaceToRecipient exit: placed={placed:0.##}");
                return placed;
            }

            var totals = days.Select(d =>
            {
                var all = GetEventsForDay(d);
                var m = calc.DailyMetrics(d, all);
                return new
                {
                    Day = d,
                    Total = m.specialNonPc + m.workInclBT
                };
            }).ToList();
            foreach (var t in totals)
                Log.Debug($"Day {t.Day:dd.MM}: total={t.Total:0.###}");
            if (!totals.Any(x => x.Total < 8.0 - 1e-6) || !totals.Any(x => x.Total > 8.0 + 1e-6))
            {
                Log.Info("Nothing to balance: no deficits or no excesses.");
                return;
            }
            var deficits = new Queue<(DateTime day, double need)>(totals
                .Where(x => x.Total < 8.0 - 1e-6)
                .Select(x => (x.Day, 8.0 - x.Total)));

            var excesses = new Queue<(DateTime day, double extra)>(totals
                .Where(x => x.Total > 8.0 + 1e-6)
                .Select(x => (x.Day, x.Total - 8.0)));
            var deniedPairs = new HashSet<(DateTime from, DateTime to)>();
            Log.Info($"Initial deficits: {string.Join(", ", deficits.Select(d => $"{d.day:dd.MM}:{d.need:0.##}"))}");
            Log.Info($"Initial excesses: {string.Join(", ", excesses.Select(e => $"{e.day:dd.MM}:{e.extra:0.##}"))}");
            int noProgressTurns = 0;
            int stallLimit = Math.Max(10, deficits.Count * Math.Max(1, excesses.Count) + 10);
            while (deficits.Count > 0 && excesses.Count > 0)
            {
                var (defDay, need) = deficits.Dequeue();
                var (exDay, extra) = excesses.Dequeue();

                Log.Info($"Loop: take from {exDay:dd.MM} extra={extra:0.##} -> put to {defDay:dd.MM} need={need:0.##}");

                var amount = Math.Min(extra, need);
                if (deniedPairs.Contains((exDay.Date, defDay.Date)))
                {
                    if (need > 1e-6) deficits.Enqueue((defDay, need));
                    if (extra > 1e-6) excesses.Enqueue((exDay, extra));
                    if (++noProgressTurns > stallLimit)
                    {
                        Log.Warn("Balance aborted: no progress (all relevant pairs denied).");
                        break;
                    }
                    continue;
                }
                var ok = await ConfirmMoveAsync(exDay, defDay, amount);
                if (!ok)
                {
                    deniedPairs.Add((exDay.Date, defDay.Date));
                    if (need > 1e-6) deficits.Enqueue((defDay, need));
                    if (extra > 1e-6) excesses.Enqueue((exDay, extra));
                    if (++noProgressTurns > stallLimit)
                    {
                        Log.Warn("Balance aborted: no progress (user denied moves).");
                        break;
                    }
                    continue;
                }
                var taken = await CutFromDonor(exDay, amount);
                Log.Info($"CutFromDonor({exDay:dd.MM}, amount={amount:0.##}) => taken={taken:0.##}");
                if (taken <= 1e-6)
                {
                    if (need > 1e-6) deficits.Enqueue((defDay, need));
                    continue;
                }

                var placed = await PlaceToRecipient(defDay, taken);
                Log.Info($"CutFromDonor({exDay:dd.MM}, amount={amount:0.##}) => taken={taken:0.##}");
                var leftNeed = Math.Max(0, need - placed);

                var leftExtra = Math.Max(0, extra - taken);
                Log.Debug($"Left: need={leftNeed:0.##}, extra={leftExtra:0.##}");
                bool progressed = (taken > 1e-6) && (placed > 1e-6);
                noProgressTurns = progressed ? 0 : (noProgressTurns + 1);

                if (placed <= 1e-6)
                {
                    leftExtra = extra;
                    if (need > 1e-6) deficits.Enqueue((defDay, need));
                }

                if (leftNeed > 1e-6) deficits.Enqueue((defDay, leftNeed));
                if (leftExtra > 1e-6) excesses.Enqueue((exDay, leftExtra));
                if (noProgressTurns > stallLimit)
                {
                    Log.Warn("Balance aborted: no progress (stall).");
                    break;
                }
                Log.Info("Balance END");
            }
        }
        private void UpdateSingleEventEnd(int eventId, DateTime newEnd)
        {
            using var db = new AppDbContext();
            var ev = db.Events.SingleOrDefault(e => e.Id == eventId && !e.IsDeleted);
            if (ev == null) return;
            if (newEnd < ev.StartTime) newEnd = ev.StartTime;
            ev.EndTime = newEnd;
            db.SaveChanges();
        }

        class DayStat
        {
            public DateTime Date;
            public List<Event> Events;
            public double Worked;
            public double Expected;
            public bool IsFixed;
        }
        private bool IsFullSpecialDay(DayStat stat, GlobalSettings g)
        {
            var only = stat.Events
                          .Where(e => e.EventType != EventType.Work
                                   && e.EventType != EventType.Lunch)
                          .ToList();
            if (only.Count != 1)
                return false;

            var (arr, dep, _, _) = PdfService.GetWeekdayDefaults(g, stat.Date.DayOfWeek);

            var e = only[0];
            return e.StartTime.TimeOfDay <= arr
                && e.EndTime.TimeOfDay >= dep;
        }
        private class BalanceItem
        {
            public DayStat Stat { get; set; }
            public double Amount { get; set; }
        }

        private void BalanceDays(List<DayStat> days)
        {
            var sem = GlobalSettingsService.GetSemesterForDate(DateTime.Today);
            var glob = GlobalSettingsService.LoadGlobalSettings(DateTime.Today.Year, sem)
                       ?? GlobalSettingsService.GetDefaultSettings(DateTime.Today.Year, sem);

            TimeSpan globalStart = TimeSpan.Parse(glob.GlobalStartTime, CultureInfo.InvariantCulture);
            TimeSpan globalEnd = TimeSpan.Parse(glob.GlobalEndTime, CultureInfo.InvariantCulture);

            var (_, _, lunchStartMon, lunchEndMon) = PdfService.GetWeekdayDefaults(glob, DayOfWeek.Monday);

            double baseDayLength = (globalEnd - globalStart).TotalHours;
            double baseLunchLength = (lunchEndMon - lunchStartMon).TotalHours;

            foreach (var stat in days)
            {
                var us = SettingsService.GetUserSettingsForDate(stat.Date);
                TimeSpan arr, dep, ls, le;
                if (us != null)
                {
                    arr = us.ArrivalTime;
                    dep = us.DepartureTime;
                    ls = us.LunchStart;
                    le = us.LunchEnd;
                }
                else
                {
                    (arr, dep, ls, le) = PdfService.GetWeekdayDefaults(glob, stat.Date.DayOfWeek);
                }

                var special = stat.Events
                    .Where(e => e.EventType != EventType.Work && e.EventType != EventType.Lunch)
                    .Select(e => (e.StartTime, e.EndTime));
                var specialMerged = MergeIntervals(special);
                double specialHours = specialMerged.Sum(iv => (iv.end - iv.start).TotalHours);

                stat.Expected = Math.Max(0, baseDayLength - baseLunchLength - specialHours);

                DateTime workWindowStart = stat.Date + arr;
                DateTime workWindowEnd = stat.Date + dep;
                var workIntervals = stat.Events
                    .Where(e => e.EventType == EventType.Work || e.EventType == EventType.BusinessTrip)
                    .Select(e => (
                        Start: e.StartTime < workWindowStart ? workWindowStart : e.StartTime,
                        End: e.EndTime > workWindowEnd ? workWindowEnd : e.EndTime));
                var mergedWork = MergeIntervals(workIntervals);
                stat.Worked = mergedWork.Sum(iv => (iv.end - iv.start).TotalHours);

            }

            var items = days.Where(d => !d.IsFixed)
                              .Select(d => new BalanceItem { Stat = d, Amount = d.Worked - d.Expected })
                              .ToList();
            var deficits = items.Where(x => x.Amount < 0).ToList();
            var excesses = items.Where(x => x.Amount > 0).ToList();
            foreach (var def in deficits)
            {
                double need = -def.Amount;
                foreach (var ex in excesses.Where(x => x.Amount > 0))
                {
                    double take = Math.Min(ex.Amount, need);
                    if (take <= 0) continue;
                    TimeSpan delta = TimeSpan.FromHours(take);

                    var donor = ex.Stat.Events
                        .Where(e => e.EventType == EventType.Work)
                        .OrderByDescending(e => e.EndTime)
                        .FirstOrDefault();
                    if (donor != null)
                    {
                        DateTime minEnd = donor.StartTime;
                        donor.EndTime = Max(donor.EndTime - delta, minEnd);
                    }

                    var gap = FindGap(def.Stat, take, globalStart, globalEnd);
                    var rec = def.Stat.Events
                        .Where(e => e.EventType == EventType.Work)
                        .OrderByDescending(e => e.EndTime)
                        .FirstOrDefault();
                    if (rec == null)
                    {
                        rec = new Event
                        {
                            Title = "Přenos z jiného dne",
                            EventType = EventType.Work,
                            StartTime = gap.start,
                            EndTime = gap.end,
                            IsAutoGenerated = true,
                            AutoGeneratedForDate = def.Stat.Date
                        };
                        CreateEvent(rec);
                        def.Stat.Events.Add(rec);
                        TimeSpan stdLunchLen = lunchEndMon - lunchStartMon;
                        var occupied = def.Stat.Events
                            .Where(e => e.EventType != EventType.Lunch)
                            .Select(e => (e.StartTime, e.EndTime))
                            .OrderBy(iv => iv.StartTime)
                            .ToList();

                        DateTime cursor = def.Stat.Date + globalStart;
                        DateTime windowEnd = def.Stat.Date + globalEnd;
                        (DateTime ls, DateTime le) lunchSlot = (default, default);

                        foreach (var iv in occupied)
                        {
                            if ((iv.StartTime - cursor) >= stdLunchLen)
                            {
                                lunchSlot = (cursor, cursor + stdLunchLen);
                                break;
                            }
                            if (iv.EndTime > cursor)
                                cursor = iv.EndTime;
                        }
                        if (lunchSlot == (default, default)
                            && windowEnd - cursor >= stdLunchLen)
                        {
                            lunchSlot = (cursor, cursor + stdLunchLen);
                        }

                        if (lunchSlot != (default, default))
                        {
                            var evLunch = GetEventsForDay(def.Stat.Date);
                            var lunchExists = evLunch.Where(e => e.EventType == EventType.Lunch
                                       && e.StartTime == e.EndTime).Select(e => (e.Id)).ToList();
                            foreach (var item in lunchExists)
                            {
                                DeleteEvent(item);
                            }
                            var lunch = new Event
                            {
                                Title = "Oběd (auto)",
                                EventType = EventType.Lunch,
                                StartTime = lunchSlot.ls,
                                EndTime = lunchSlot.le,
                                IsAutoGenerated = true,
                                AutoGeneratedForDate = def.Stat.Date
                            };
                            CreateEvent(lunch);
                            def.Stat.Events.Add(lunch);
                        }
                    }
                    else
                    {
                        DateTime maxEnd = def.Stat.Date + globalEnd;
                        var oldEnd = rec.EndTime;
                        rec.EndTime = Min(rec.EndTime + delta, maxEnd);
                    }

                    ex.Amount -= take;
                    need -= take;
                    if (need <= 0) break;
                }
            }
        }
        static DateTime Min(DateTime a, DateTime b) => a < b ? a : b;
        static DateTime Max(DateTime a, DateTime b) => a > b ? a : b;
        private List<(DateTime start, DateTime end)> MergeIntervals(IEnumerable<(DateTime start, DateTime end)> intervals)
        {
            var sorted = intervals.OrderBy(x => x.start).ToList();
            var merged = new List<(DateTime start, DateTime end)>();
            foreach (var seg in sorted)
            {
                if (!merged.Any() || merged.Last().end < seg.start)
                    merged.Add(seg);
                else
                    merged[^1] = (
                        merged.Last().start,
                        merged.Last().end > seg.end ? merged.Last().end : seg.end
                    );
            }
            return merged;
        }

        private (DateTime start, DateTime end) FindGap(DayStat stat, double hours, TimeSpan globalStart, TimeSpan globalEnd)
        {
            var occupied = stat.Events
                .Select(e => (e.StartTime, e.EndTime))
                .OrderBy(iv => iv.StartTime)
                .ToList();

            DateTime cursor = stat.Date + globalStart;
            DateTime windowEnd = stat.Date + globalEnd;

            foreach (var iv in occupied)
            {
                if ((iv.StartTime - cursor).TotalHours >= hours)
                    return (cursor, cursor.AddHours(hours));

                if (iv.EndTime > cursor)
                    cursor = iv.EndTime;
            }

            if ((windowEnd - cursor).TotalHours >= hours)
                return (cursor, cursor.AddHours(hours));

            throw new InvalidOperationException(
                $"Žádné volné místo na {hours:F2}h v {stat.Date:yyyy-MM-dd}");
        }
        private async Task<double> TrimDonorFromEndByUnionAsync(DateTime day, double hoursToCut)
        {
            if (hoursToCut <= 1e-6) return 0;

            var all = GetEventsForDay(day);
            var (arr, dep, _, _) = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false)).GetType()
                .GetMethod("GetWindow", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance) is { } ? (TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero) : (TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero);
            var sem = GlobalSettingsService.GetSemesterForDate(day);
            var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                      ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var def = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);
            var us = SettingsService.GetUserSettingsForDate(day);
            var winS = day + (us?.ArrivalTime ?? def.arrival);
            var winE = day + (us?.DepartureTime ?? def.departure);

            var workLike = all.Where(e => (e.EventType == EventType.Work || e.EventType == EventType.BusinessTrip) && !e.IsDeleted);
            var merged = BuildMergedWithOwners(workLike, winS, winE);
            if (merged.Count == 0) return 0;

            double cutLeft = hoursToCut;

            for (int i = merged.Count - 1; i >= 0 && cutLeft > 1e-6; i--)
            {
                var segS = merged[i].s;
                var segE = merged[i].e;
                var owners = merged[i].owners.Distinct().OrderByDescending(ev => ev.EndTime).ToList();

                double segLenH = (segE - segS).TotalHours;
                double take = Math.Min(segLenH, cutLeft);

                DateTime newEndLimit = segE.AddHours(-take);
                foreach (var ev in owners)
                {
                    if (ev.EndTime <= newEndLimit) continue;
                    var newEnd = newEndLimit > ev.StartTime ? newEndLimit : ev.StartTime;
                    if (newEnd < ev.EndTime)
                        UpdateSingleEventEnd(ev.Id, newEnd);
                }

                cutLeft -= take;
            }

            var cutDone = hoursToCut - cutLeft;

            if (cutDone > 1e-6)
            {
                var us2 = SettingsService.GetUserSettingsForDate(day);
                var depT = (us2?.DepartureTime ?? def.departure) - TimeSpan.FromHours(cutDone);
                if (depT < (us2?.ArrivalTime ?? def.arrival)) depT = (us2?.ArrivalTime ?? def.arrival);

                TimeSpan ls = us2?.LunchStart ?? def.lunchStart;
                TimeSpan le = us2?.LunchEnd ?? def.lunchEnd;
                if (le > ls && (le > depT || ls < (us2?.ArrivalTime ?? def.arrival)))
                    (ls, le) = (TimeSpan.Zero, TimeSpan.Zero);

                SettingsService.SaveUserSettingsForDate(day, us2?.ArrivalTime ?? def.arrival, depT, ls, le);
                ReplaceLunchEvent(day, ls, le);

                var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
                await gen.RegenerateDailyEventsAsync(day);
            }

            return cutDone;
        }
        private void DeleteLunchEvents(DateTime day)
        {
            using var db = new AppDbContext();
            var lunches = db.Events
                .Where(e => !e.IsDeleted &&
                            e.StartTime.Date == day.Date &&
                            e.EventType == EventType.Lunch)
                .ToList();
            if (lunches.Count > 0)
            {
                db.Events.RemoveRange(lunches);
                db.SaveChanges();
            }
        }

        private void ReplaceLunchEvent(DateTime day, TimeSpan ls, TimeSpan le)
        {
            DeleteLunchEvents(day);
            if (le > ls)
            {
                using var db = new AppDbContext();
                db.Events.Add(new Event
                {
                    Title = "Oběd (auto)",
                    EventType = EventType.Lunch,
                    StartTime = day + ls,
                    EndTime = day + le,
                    IsAutoGenerated = true,
                    AutoGeneratedForDate = day.Date
                });
                db.SaveChanges();
            }
        }
        public record ImportBatchInfo(string Id, string Label, DateTime RangeStart, DateTime RangeEnd, int EventsCount);

        public IEnumerable<ImportBatchInfo> GetImportBatches()
        {
            using var db = new AppDbContext();

            var rows = db.Events
                .Where(e => !e.IsDeleted && e.ImportBatchId != null)
                .GroupBy(e => new { e.ImportBatchId, e.ImportLabel })
                .Select(g => new
                {
                    Id = g.Key.ImportBatchId!,
                    Label = g.Key.ImportLabel,
                    RangeStart = g.Min(e => e.StartTime),
                    RangeEnd = g.Max(e => e.EndTime),
                    EventsCount = g.Count()
                })
                .OrderByDescending(x => x.RangeStart)
                .AsNoTracking()
                .ToList();

            return rows
                .Select(x => new ImportBatchInfo(
                    x.Id,
                    x.Label ?? "Načtení",
                    x.RangeStart.Date,
                    x.RangeEnd.Date,
                    x.EventsCount))
                .ToList();
        }

        public void DeleteEventsByImportId(string batchId)
        {
            var toDelete = GetAllEvents()
                .Where(e => e.ImportBatchId == batchId)
                .ToList();

            foreach (var ev in toDelete)
                DeleteEvent(ev.Id);
        }
        public void DeleteEventCascadeAndCleanup(int id)
        {
            using var db = new AppDbContext();

            var toDelete = db.Events
                .Where(e => e.Id == id || e.ParentEventId == id)
                .ToList();

            if (toDelete.Count == 0) return;

            var affectedDates = toDelete
                .Select(e => e.StartTime.Date)
                .Distinct()
                .ToList();

            foreach (var e in toDelete)
                e.IsDeleted = true;

            db.SaveChanges();

            foreach (var day in affectedDates)
            {
                bool anyLeft = db.Events.Any(e => !e.IsDeleted && e.StartTime.Date == day);
                if (!anyLeft)
                {
                    SettingsService.DeleteUserSettingsForDate(day);
                    continue;
                }

                AdjustUserSettingsAfterDeletion(day);

                var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
                gen.RegenerateDailyEventsAsync(day).GetAwaiter().GetResult();

                MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
                MessageBus.Current.SendMessage(new UserSettingsChangedMessage(day));
            }
        }
        private void AdjustUserSettingsAfterDeletion(DateTime day)
        {
            var events = GetEventsForDay(day)
                .Where(e => e.EventType != EventType.Lunch)
                .OrderBy(e => e.StartTime)
                .ToList();

            if (events.Count == 0)
            {
                SettingsService.DeleteUserSettingsForDate(day);
                return;
            }

            var firstStart = events.First().StartTime;
            var lastEnd = events.Last().EndTime;

            var sem = GlobalSettingsService.GetSemesterForDate(day);
            var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                     ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var def = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);
            var us = SettingsService.GetUserSettingsForDate(day);

            var arr = firstStart.TimeOfDay;
            var dep = lastEnd.TimeOfDay;

            TimeSpan ls = TimeSpan.Zero, le = TimeSpan.Zero;
            if (us != null && us.LunchEnd > us.LunchStart)
            {
                if (us.LunchStart >= arr && us.LunchEnd <= dep)
                {
                    ls = us.LunchStart; le = us.LunchEnd;
                }
            }
            else if (def.lunchEnd > def.lunchStart && def.lunchStart >= arr && def.lunchEnd <= dep)
            {
                ls = def.lunchStart; le = def.lunchEnd;
            }

            SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
        }

        public async Task TrimOvertimeByAutoBlocksAsync(DateTime day)
        {
            var calc = new WorkingHoursCalculatorService();
            var all = GetEventsForDay(day);
            var m = calc.DailyMetrics(day, all);
            var over = Math.Max(0, (m.specialNonPc + m.workInclBT) - 8.0);
            if (over <= 1e-6) return;

            var lastAuto = all
                .Where(e => e.IsAutoGenerated && e.EventType == EventType.Work && !e.IsDeleted)
                .OrderByDescending(e => e.EndTime)
                .FirstOrDefault();

            if (lastAuto != null)
            {
                var cut = Math.Min(over, (lastAuto.EndTime - lastAuto.StartTime).TotalHours);
                if (cut > 1e-6)
                {
                    var newEnd = lastAuto.EndTime - TimeSpan.FromHours(cut);
                    if (newEnd < lastAuto.StartTime) newEnd = lastAuto.StartTime;

                    UpdateSingleEventEnd(lastAuto.Id, newEnd);

                    var us = SettingsService.GetUserSettingsForDate(day);
                    var sem = GlobalSettingsService.GetSemesterForDate(day);
                    var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                             ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
                    var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);

                    var arr = us?.ArrivalTime ?? defArr;
                    var dep = us?.DepartureTime ?? defDep;
                    var ls = us?.LunchStart ?? defLs;
                    var le = us?.LunchEnd ?? defLe;

                    dep = newEnd.TimeOfDay > arr ? newEnd.TimeOfDay : arr;

                    if (le > ls && (le > dep || ls < arr))
                    {
                        var len = le - ls;
                        var nls = dep - len;
                        if (nls >= arr)
                            (ls, le) = (nls, dep);
                        else
                            (ls, le) = (TimeSpan.Zero, TimeSpan.Zero);
                    }

                    SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
                    ReplaceLunchEvent(day, ls, le);
                    var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(true));
                    await gen.RegenerateDailyEventsAsync(day);
                    return;
                }
            }

            var firstAuto = all
                .Where(e => e.IsAutoGenerated && e.EventType == EventType.Work && !e.IsDeleted)
                .OrderBy(e => e.StartTime)
                .FirstOrDefault();

            if (firstAuto != null)
            {
                var cut = Math.Min(over, (firstAuto.EndTime - firstAuto.StartTime).TotalHours);
                if (cut > 1e-6)
                {
                    var newStart = firstAuto.StartTime + TimeSpan.FromHours(cut);
                    if (newStart > firstAuto.EndTime) newStart = firstAuto.EndTime;

                    using (var db = new AppDbContext())
                    {
                        var ev = db.Events.Single(x => x.Id == firstAuto.Id);
                        ev.StartTime = newStart;
                        db.SaveChanges();
                    }

                    var us = SettingsService.GetUserSettingsForDate(day);
                    var sem = GlobalSettingsService.GetSemesterForDate(day);
                    var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                             ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
                    var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);

                    var arr = us?.ArrivalTime ?? defArr;
                    var dep = us?.DepartureTime ?? defDep;
                    var ls = us?.LunchStart ?? defLs;
                    var le = us?.LunchEnd ?? defLe;

                    arr = newStart.TimeOfDay < dep ? newStart.TimeOfDay : dep;

                    if (le > ls && (le > dep || ls < arr))
                    {
                        var len = le - ls;
                        var nle = arr + len;
                        if (nle <= dep)
                            (ls, le) = (arr, nle);
                        else
                            (ls, le) = (TimeSpan.Zero, TimeSpan.Zero);
                    }

                    SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
                    ReplaceLunchEvent(day, ls, le);
                    var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(true));
                    await gen.RegenerateDailyEventsAsync(day);
                }
            }
        }
    }
    static class Log
    {
        private static readonly object _lock = new object();
        private static string _path;
        private static bool _enabled = true;

        public static void Init(string name = "balance")
        {
            try
            {
                var dir = Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                    "TeacherScheduleApp", "logs");
                Directory.CreateDirectory(dir);
                var ts = DateTime.Now.ToString("yyyyMMdd-HHmmss");
                _path = Path.Combine(dir, $"{name}-{ts}.txt");
                WriteLine($"=== NEW SESSION {DateTime.Now:yyyy-MM-dd HH:mm:ss.fff} ===");
                WriteLine($"PID={Environment.ProcessId}, Thread={Environment.CurrentManagedThreadId}");
            }
            catch { /* ignore */ }
        }

        public static void Enable(bool enabled) => _enabled = enabled;

        public static void WriteLine(string msg)
        {
            if (!_enabled) return;
            lock (_lock)
            {
                try
                {
                    if (string.IsNullOrEmpty(_path)) Init();
                    File.AppendAllText(_path,
                        $"{DateTime.Now:HH:mm:ss.fff} [T{Environment.CurrentManagedThreadId}] {msg}\r\n",
                        Encoding.UTF8);
                }
                catch { }
            }
        }

        public static void Info(string msg) => WriteLine("[INFO]  " + msg);
        public static void Warn(string msg) => WriteLine("[WARN]  " + msg);
        public static void Error(string msg) => WriteLine("[ERROR] " + msg);
        public static void Debug(string msg) => WriteLine("[DEBUG] " + msg);
    }
}
