using Microsoft.EntityFrameworkCore;
using ReactiveUI;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TeacherScheduleApp.Data;
using TeacherScheduleApp.Helpers;
using TeacherScheduleApp.Messages;
using TeacherScheduleApp.Models;

namespace TeacherScheduleApp.Services
{
    class MoveLunchState { public bool? State; }
    public class EventService
    {   
        private static List<(DateTime s, DateTime e, List<Event> owners)>BuildMergedWithOwners(IEnumerable<Event> evs, DateTime winS, DateTime winE)
        {
            var segs = evs
                .Select(e => (
                    s: e.StartTime < winS ? winS : e.StartTime,
                    e: e.EndTime > winE ? winE : e.EndTime,
                    ev: e))
                .Where(x => x.e > x.s)
                .OrderBy(x => x.s)
                .ToList();

            var merged = new List<(DateTime s, DateTime e, List<Event> owners)>();
            foreach (var seg in segs)
            {
                if (merged.Count == 0 || merged[^1].e < seg.s)
                    merged.Add((seg.s, seg.e, new List<Event> { seg.ev }));
                else
                {
                    if (seg.e > merged[^1].e) merged[^1] = (merged[^1].s, seg.e, merged[^1].owners);
                    merged[^1].owners.Add(seg.ev);
                }
            }
            return merged;
        }
        public void CreateEvent(Event ev)
        {
            if (ev.IsAutoGenerated)
            {
                using var dbContext = new AppDbContext();
                dbContext.Events.Add(ev);
                dbContext.SaveChanges();
                return;
            }
            DateTime parentDate = ev.StartTime.Date;
            while (parentDate <= ev.EndTime.Date && (parentDate.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday || HolidayHelper.IsCzechHoliday(parentDate)))
            {
                parentDate = parentDate.AddDays(1);
            }
            if (parentDate > ev.EndTime.Date)
                return;

            using var db = new AppDbContext();

            var parent = new Event
            {
                Title = ev.Title,
                Description = ev.Description,
                EventType = ev.EventType,
                AllDay = ev.AllDay,
                StartTime = parentDate + ev.StartTime.TimeOfDay,
                EndTime = parentDate + ev.EndTime.TimeOfDay,
                ArrivalTime = parentDate + ev.ArrivalTime.TimeOfDay,
                DepartureTime = parentDate + ev.DepartureTime.TimeOfDay,
                LunchStart = parentDate + ev.LunchStart.TimeOfDay,
                LunchEnd = parentDate + ev.LunchEnd.TimeOfDay,
                ParentEventId = null,
                IsAutoGenerated = ev.IsAutoGenerated,
                ImportBatchId = ev.ImportBatchId,
                ImportLabel = ev.ImportLabel

            };
            db.Events.Add(parent);
            db.SaveChanges();

            for (var day = parentDate.AddDays(1); day <= ev.EndTime.Date; day = day.AddDays(1))
            {
                if (day.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday || HolidayHelper.IsCzechHoliday(day))
                    continue;

                var child = new Event
                {
                    Title = ev.Title,
                    Description = ev.Description,
                    EventType = ev.EventType,
                    AllDay = ev.AllDay,
                    StartTime = day + ev.StartTime.TimeOfDay,
                    EndTime = day + ev.EndTime.TimeOfDay,
                    ArrivalTime = day + ev.ArrivalTime.TimeOfDay,
                    DepartureTime = day + ev.DepartureTime.TimeOfDay,
                    LunchStart = day + ev.LunchStart.TimeOfDay,
                    LunchEnd = day + ev.LunchEnd.TimeOfDay,
                    ParentEventId = parent.Id,
                    IsAutoGenerated = ev.IsAutoGenerated,
                    ImportBatchId = ev.ImportBatchId,
                    ImportLabel = ev.ImportLabel
                };
                db.Events.Add(child);
            }
            db.SaveChanges();

            var affectedDates = Enumerable
                .Range(0, (ev.EndTime.Date - parentDate).Days + 1)
                .Select(offset => parentDate.AddDays(offset))
                .Where(d => d.DayOfWeek is not DayOfWeek.Saturday and not DayOfWeek.Sunday
                         && !HolidayHelper.IsCzechHoliday(d))
                .ToList();

            var autos = db.Events
                .Where(x => x.IsAutoGenerated
                         && x.AutoGeneratedForDate.HasValue
                         && affectedDates.Contains(x.AutoGeneratedForDate.Value.Date))
                .ToList();
            db.Events.RemoveRange(autos);
            db.SaveChanges();

            var sem = GlobalSettingsService.GetSemesterForDate(parentDate);
            var glob = GlobalSettingsService.LoadGlobalSettings(parentDate.Year, sem)
                        ?? GlobalSettingsService.GetDefaultSettings(parentDate.Year, sem);
            var gStart = TimeSpan.Parse(glob.GlobalStartTime);
            var gEnd = TimeSpan.Parse(glob.GlobalEndTime);
            var norm = gEnd - gStart;

            var manualSpan = ev.AllDay ? norm : (ev.EndTime.TimeOfDay - ev.StartTime.TimeOfDay);

         
            var autoGen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false)
            );
            foreach (var d in affectedDates)
            {
                autoGen.RegenerateDailyEventsAsync(d).Wait();
            }
        }

        public List<Event> GetAllEvents()
        {
            using var db = new AppDbContext();
            return db.Events.ToList();
        }

        public int SoftDeleteImportedInRange(DateTime startIncl, DateTime endIncl)
        {
            using var db = new AppDbContext();
            db.ChangeTracker.AutoDetectChangesEnabled = false;

            var toDel = db.Events
                .Where(e => !e.IsDeleted
                         && e.ImportBatchId != null
                         && e.StartTime.Date >= startIncl.Date
                         && e.StartTime.Date <= endIncl.Date)
                .ToList();

            foreach (var e in toDel) e.IsDeleted = true;
            db.SaveChanges();
            return toDel.Count;
        }

        public void RemoveAutoGeneratedEvents(DateTime date)
        {
            using var db = new AppDbContext();
            var evs = db.Events
                .Where(e => e.IsAutoGenerated && e.AutoGeneratedForDate == date.Date)
                .ToList();
            db.Events.RemoveRange(evs);
            db.SaveChanges();
        }

        public List<Event> LoadEvents()
        {
            using (var context = new AppDbContext())
            {
                return context.Events
                              .Where(e => !e.IsDeleted)
                              .ToList();
            }
        }
        public void CreateEventsBulk(IEnumerable<Event> events)
        {
            using var db = new AppDbContext();
            db.ChangeTracker.AutoDetectChangesEnabled = false;
            db.Events.AddRange(events);          
            db.SaveChanges();
        }

        public Event GetEventById(int id)
        {
            using var db = new AppDbContext();
            return db.Events.Find(id);
        }

        public void UpdateEvent(Event ev, bool suppressRegen = false)
        {
            using var db = new AppDbContext();
            var parent = db.Events.SingleOrDefault(x => x.Id == ev.Id);
            if (parent == null)
                return;

            var oldEndDate = parent.EndTime.Date;
            parent.Title = ev.Title;
            parent.StartTime = ev.StartTime;
            parent.EndTime = ev.EndTime;
            parent.AllDay = ev.AllDay;
            parent.Description = ev.Description;
            parent.IsDeleted = ev.IsDeleted;
            parent.EventType = ev.EventType;
            parent.ArrivalTime = ev.ArrivalTime;
            parent.DepartureTime = ev.DepartureTime;
            parent.LunchStart = ev.LunchStart;
            parent.LunchEnd = ev.LunchEnd;
            parent.IsAutoGenerated = ev.IsAutoGenerated;
            parent.HasCollision = ev.HasCollision;
            parent.AutoGeneratedForDate = ev.AutoGeneratedForDate;
            db.SaveChanges();

            var oldChildren = db.Events.Where(c => c.ParentEventId == parent.Id).ToList();
            if (oldChildren.Any())
            {
                db.Events.RemoveRange(oldChildren);
                db.SaveChanges();
            }

            DateTime start = parent.StartTime.Date.AddDays(1);
            for (var day = start; day <= ev.EndTime.Date; day = day.AddDays(1))
            {
                if (day.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday
                 || HolidayHelper.IsCzechHoliday(day))
                    continue;

                var child = new Event
                {
                    Title = parent.Title,
                    Description = parent.Description,
                    EventType = parent.EventType,
                    AllDay = parent.AllDay,
                    StartTime = day + parent.StartTime.TimeOfDay,
                    EndTime = day + parent.EndTime.TimeOfDay,
                    ArrivalTime = day + parent.ArrivalTime.TimeOfDay,
                    DepartureTime = day + parent.DepartureTime.TimeOfDay,
                    LunchStart = day + parent.LunchStart.TimeOfDay,
                    LunchEnd = day + parent.LunchEnd.TimeOfDay,
                    ParentEventId = parent.Id,
                    IsAutoGenerated = parent.IsAutoGenerated
                };
                db.Events.Add(child);
            }
            db.SaveChanges();
            if (!suppressRegen)
            {
                var dayToRegen = parent.StartTime.Date;
                var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
                gen.RegenerateDailyEventsAsync(dayToRegen).GetAwaiter().GetResult();
                MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
                MessageBus.Current.SendMessage(new UserSettingsChangedMessage(dayToRegen));
            }
        }

        public void DeleteEvent(int id)
        {
            using var db = new AppDbContext();
            var ev = db.Events.FirstOrDefault(e => e.Id == id);
            if (ev == null) return;

            var day = ev.StartTime.Date;

            ev.IsDeleted = true;
            db.SaveChanges();

            AdjustUserSettingsAfterDeletion(day);

            var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
            gen.RegenerateDailyEventsAsync(day).GetAwaiter().GetResult();

            MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
            MessageBus.Current.SendMessage(new UserSettingsChangedMessage(day));
        }

        public List<Event> GetEventsForDay(DateTime date)
        {
            using var db = new AppDbContext();
            return db.Events
                     .Where(e => e.StartTime.Date == date.Date && !e.IsDeleted)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }

        public List<Event> GetEventsForWeek(DateTime anyDate)
        {
            var date = anyDate.Date;
            int delta = (int)date.DayOfWeek - (int)DayOfWeek.Monday;
            if (delta < 0) delta += 7;
            var weekStart = date.AddDays(-delta);

            var weekEnd = weekStart.AddDays(7);


            using var db = new AppDbContext();
            return db.Events
                     .Where(e =>
                         !e.IsDeleted &&
                         e.StartTime < weekEnd &&
                         e.EndTime >= weekStart)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }


        public List<Event> GetEventsForMonth(DateTime date)
        {
            using var db = new AppDbContext();
            var year = date.Year;
            var month = date.Month;
            return db.Events
                     .Where(e =>
                         e.StartTime.Year == year &&
                         e.StartTime.Month == month &&
                         !e.IsDeleted)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }
        public List<Event> GetEventsForRange(DateTime start, DateTime end)
        {
            using var db = new AppDbContext();
            return db.Events
                     .Where(e => e.StartTime < end && e.EndTime >= start && !e.IsDeleted)
                     .OrderBy(e => e.StartTime)
                     .ToList();
        }
        public Event? FindEventByStartTime(DateTime startTime)
        {
            using var db = new AppDbContext();
            return db.Events.FirstOrDefault(e => e.StartTime == startTime && !e.IsDeleted);
        }

        public void CreateAutoEvent(Event ev)
        {
            using var db = new AppDbContext();
            db.Events.Add(ev);
            db.SaveChanges();
        }


        private (Event? firstAuto, Event? lastAuto) GetEdgeAutoBlocks(DateTime day)
        {
            var evs = GetEventsForDay(day)
                .Where(e => e.EventType == EventType.Work && e.IsAutoGenerated && !e.IsDeleted)
                .OrderBy(e => e.StartTime)
                .ToList();

            return (evs.FirstOrDefault(), evs.LastOrDefault());
        }

        private (bool canShortenStart, bool canShortenEnd) CanShortenDay(DateTime day)
        {
            var evs = GetEventsForDay(day).Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                                          .OrderBy(e => e.StartTime).ToList();
            if (!evs.Any()) return (true, true);

            bool firstIsAuto = evs.First().IsAutoGenerated && evs.First().EventType == EventType.Work;
            bool lastIsAuto = evs.Last().IsAutoGenerated && evs.Last().EventType == EventType.Work;
            return (firstIsAuto, lastIsAuto);
        }

        private double TrimAutoFromEnd(DateTime day, double hoursToCut)
        {
            if (hoursToCut <= 1e-6) return 0;

            var evs = GetEventsForDay(day)
                .Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                .OrderBy(e => e.EndTime)
                .ToList();

            var last = evs.LastOrDefault();
            if (!(last?.IsAutoGenerated == true && last.EventType == EventType.Work))
            {
                return 0;
            }

            double left = hoursToCut;
            using (var db = new AppDbContext())
            {
                while (left > 1e-6)
                {
                    var lastAuto = db.Events
                        .Where(e => !e.IsDeleted
                                 && e.StartTime.Date == day.Date
                                 && e.EventType == EventType.Work
                                 && e.IsAutoGenerated)
                        .OrderByDescending(e => e.EndTime)
                        .FirstOrDefault();

                    if (lastAuto == null) { break; }

                    var len = (lastAuto.EndTime - lastAuto.StartTime).TotalHours;
                    if (len <= 1e-6) { lastAuto.IsDeleted = true; db.SaveChanges(); continue; }

                    var take = Math.Min(len, left);
                    lastAuto.EndTime = lastAuto.EndTime - TimeSpan.FromHours(take);

                    if (lastAuto.EndTime <= lastAuto.StartTime) lastAuto.IsDeleted = true;

                    db.SaveChanges();
                    left -= take;

                    var newLast = db.Events
                        .Where(e => !e.IsDeleted
                                 && e.StartTime.Date == day.Date
                                 && e.EventType != EventType.Lunch)
                        .OrderByDescending(e => e.EndTime)
                        .FirstOrDefault();

                    if (!(newLast?.IsAutoGenerated == true && newLast.EventType == EventType.Work))
                        break;
                }
            }

            var cut = hoursToCut - left;

            if (cut > 1e-6)
            {
                var sem = GlobalSettingsService.GetSemesterForDate(day);
                var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                         ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
                var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);
                var us = SettingsService.GetUserSettingsForDate(day);
                var arr = us?.ArrivalTime ?? defArr;

                var lastEnd = GetEventsForDay(day)
                    .Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                    .Select(e => e.EndTime)
                    .DefaultIfEmpty(day + arr)
                    .Max()
                    .TimeOfDay;

                var dep = lastEnd;

                var (ls, le) = RefitLunch(day, arr, dep, us?.LunchStart ?? defLs, us?.LunchEnd ?? defLe, (defLe > defLs ? defLe - defLs : TimeSpan.FromMinutes(30)));

                SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
                ReplaceLunchEvent(day, ls, le);
            }

            return cut;
        }



        private double TrimAutoFromStart(DateTime day, double hoursToCut)
        {
            if (hoursToCut <= 1e-6) return 0;

            var evs = GetEventsForDay(day)
                .Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                .OrderBy(e => e.StartTime)
                .ToList();

            var first = evs.FirstOrDefault();
            if (!(first?.IsAutoGenerated == true && first.EventType == EventType.Work))
            {
                return 0;
            }

            double left = hoursToCut;
            using (var db = new AppDbContext())
            {
                while (left > 1e-6)
                {
                    var firstAuto = db.Events
                        .Where(e => !e.IsDeleted
                                 && e.StartTime.Date == day.Date
                                 && e.EventType == EventType.Work
                                 && e.IsAutoGenerated)
                        .OrderBy(e => e.StartTime)
                        .FirstOrDefault();

                    if (firstAuto == null) { break; }

                    var len = (firstAuto.EndTime - firstAuto.StartTime).TotalHours;
                    if (len <= 1e-6) { firstAuto.IsDeleted = true; db.SaveChanges(); continue; }

                    var take = Math.Min(len, left);
                    firstAuto.StartTime = firstAuto.StartTime + TimeSpan.FromHours(take);

                    if (firstAuto.EndTime <= firstAuto.StartTime) firstAuto.IsDeleted = true;

                    db.SaveChanges();
                    left -= take;

                    var newFirst = db.Events
                        .Where(e => !e.IsDeleted
                                 && e.StartTime.Date == day.Date
                                 && e.EventType != EventType.Lunch)
                        .OrderBy(e => e.StartTime)
                        .FirstOrDefault();

                    if (!(newFirst?.IsAutoGenerated == true && newFirst.EventType == EventType.Work))
                        break;
                }
            }

            var cut = hoursToCut - left;

            if (cut > 1e-6)
            {
                var sem = GlobalSettingsService.GetSemesterForDate(day);
                var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                         ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
                var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);
                var us = SettingsService.GetUserSettingsForDate(day);
                var dep = us?.DepartureTime ?? defDep;

                var firstStart = GetEventsForDay(day)
                    .Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                    .Select(e => e.StartTime)
                    .DefaultIfEmpty(day + dep)
                    .Min()
                    .TimeOfDay;

                var arr = firstStart;

                var (ls, le) = RefitLunch(day, arr, dep, us?.LunchStart ?? defLs, us?.LunchEnd ?? defLe, (defLe > defLs ? defLe - defLs : TimeSpan.FromMinutes(30)));

                SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
                ReplaceLunchEvent(day, ls, le);
            }

            return cut;
        }
        private List<(DateTime s, DateTime e)> GetBusyIntervals(DateTime day, TimeSpan arr, TimeSpan dep)
        {
            var winS = day + arr;
            var winE = day + dep;
            return GetEventsForDay(day)
                .Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                .Select(e => (s: e.StartTime < winS ? winS : e.StartTime,
                              e: e.EndTime > winE ? winE : e.EndTime))
                .Where(x => x.e > x.s)
                .OrderBy(x => x.s)
                .ToList();
        }


        private (TimeSpan ls, TimeSpan le) RefitLunch(DateTime day, TimeSpan arr, TimeSpan dep,
                                                      TimeSpan desiredLs, TimeSpan desiredLe,
                                                      TimeSpan fallbackLen)
        {
            var len = desiredLe > desiredLs ? (desiredLe - desiredLs) : fallbackLen;
            if (dep <= arr || len <= TimeSpan.Zero) return (TimeSpan.Zero, TimeSpan.Zero);

            var busy = GetBusyIntervals(day, arr, dep);

            bool Fits(DateTime s, DateTime e)
                => !busy.Any(iv => !(e <= iv.s || s >= iv.e));

            var c1e = day + dep;
            var c1s = c1e - len;
            if (c1s >= day + arr && Fits(c1s, c1e))
                return (c1s.TimeOfDay, c1e.TimeOfDay);

            var c2s = day + arr;
            var c2e = c2s + len;
            if (c2e <= day + dep && Fits(c2s, c2e))
                return (c2s.TimeOfDay, c2e.TimeOfDay);

            DateTime cursor = day + arr;
            foreach (var iv in busy)
            {
                if (iv.s > cursor && (iv.s - cursor) >= len)
                    return (cursor.TimeOfDay, (cursor + len).TimeOfDay);
                if (iv.e > cursor) cursor = iv.e;
            }
            if (day + dep > cursor && (day + dep - cursor) >= len)
                return (cursor.TimeOfDay, (cursor + len).TimeOfDay);

            return (TimeSpan.Zero, TimeSpan.Zero);
        }

        private double ExtendDayWithAuto(DateTime day, double hours)
        {
            if (hours <= 1e-6) return 0;

            var evs = GetEventsForDay(day).Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                                          .OrderBy(e => e.StartTime).ToList();

            var sem = GlobalSettingsService.GetSemesterForDate(day);
            var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                      ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var us = SettingsService.GetUserSettingsForDate(day);
            var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);

            var arr = us?.ArrivalTime ?? defArr;
            var dep = us?.DepartureTime ?? defDep;

            var lastEnd = evs.Any() ? evs.Last().EndTime : (day + dep);
            var segS = lastEnd;
            var segE = lastEnd.AddHours(hours);

            CreateAutoEvent(new Event
            {
                Title = "Vyvažování práce",
                EventType = EventType.Work,
                StartTime = segS,
                EndTime = segE,
                IsAutoGenerated = true,
                AutoGeneratedForDate = day
            });

            var newDep = segE.TimeOfDay;

            var (nls, nle) = RefitLunch(day, arr, newDep,
                                        us?.LunchStart ?? defLs, us?.LunchEnd ?? defLe,
                                        (defLe > defLs ? defLe - defLs : TimeSpan.FromMinutes(30)));

            if (nle <= nls)
            {
                var desiredLen = (defLe > defLs ? defLe - defLs : TimeSpan.FromMinutes(30));
                if (TryCarveLunchFromInnerAuto(day, arr, newDep, desiredLen, out var cls, out var cle))
                {
                    nls = cls; nle = cle;
                }
            }

            SettingsService.SaveUserSettingsForDate(day, arr, newDep, nls, nle);

            ReplaceLunchEvent(day, nls, nle);
            return hours;
        }

        private bool TryCarveLunchFromInnerAuto(DateTime day,
                                        TimeSpan arr,
                                        TimeSpan dep,
                                        TimeSpan len,
                                        out TimeSpan ls,
                                        out TimeSpan le)
        {
            ls = le = TimeSpan.Zero;
            if (dep <= arr || len <= TimeSpan.Zero) return false;

            var all = GetEventsForDay(day)
                .Where(e => !e.IsDeleted && e.EventType != EventType.Lunch)
                .OrderBy(e => e.StartTime)
                .ToList();

            if (all.Count < 3) return false; 

           
            var candidate = all
                .Skip(1).Take(all.Count - 2) 
                .FirstOrDefault(e =>
                    e.IsAutoGenerated &&
                    e.EventType == EventType.Work &&
                    (e.EndTime - e.StartTime) >= len + TimeSpan.FromMinutes(1) &&
                    e.StartTime >= day + arr &&
                    e.EndTime <= day + dep);

            if (candidate == null) return false;

            var cutStart = candidate.StartTime;
            var cutEnd = candidate.StartTime + len; 

           
            var idx = all.FindIndex(x => x.Id == candidate.Id);
            if (idx <= 0 || idx >= all.Count - 1) return false;
            var prevEnd = all[idx - 1].EndTime;
            var nextStart = all[idx + 1].StartTime;
            if (cutStart < prevEnd || cutEnd > nextStart) return false; 

            using (var db = new AppDbContext())
            {
                var ev = db.Events.Single(x => x.Id == candidate.Id && !x.IsDeleted);
                ev.StartTime = cutEnd;
                if (ev.EndTime < ev.StartTime) ev.EndTime = ev.StartTime; 
                db.SaveChanges();
            }

            CreateAutoEvent(new Event
            {
                Title = "Oběd (auto)",
                EventType = EventType.Lunch,
                StartTime = cutStart,
                EndTime = cutEnd,
                IsAutoGenerated = true,
                AutoGeneratedForDate = day
            });

            ls = cutStart.TimeOfDay;
            le = cutEnd.TimeOfDay;
            return true;
        }
        public async Task BalanceEventsForMonthAsync(int year, int month, Func<string, Task<bool>> _)
        {

            var monthStart = new DateTime(year, month, 1);
            var monthEnd = new DateTime(year, month, DateTime.DaysInMonth(year, month));

            static DateTime WeekStart(DateTime d)
            {
                int delta = (int)d.DayOfWeek - (int)DayOfWeek.Monday;
                if (delta < 0) delta += 7;
                return d.Date.AddDays(-delta);
            }

            var workDays = Enumerable.Range(0, (monthEnd - monthStart).Days + 1)
                .Select(i => monthStart.AddDays(i))
                .Where(d => d.DayOfWeek is not DayOfWeek.Saturday and not DayOfWeek.Sunday
                            && !HolidayHelper.IsCzechHoliday(d))
                .ToList();

            var byWeek = workDays.GroupBy(WeekStart)
                                 .OrderBy(g => g.Key)
                                 .ToList();

            var calc = new WorkingHoursCalculatorService();

            double DayWorked(DateTime d)
            {
                var m = calc.DailyMetrics(d, GetEventsForDay(d));
                return m.workInclBT;
            }

            foreach (var g in byWeek)
            {
                var daysInWeek = g.ToList();
                double weekQuota = 8.0 * daysInWeek.Count;

                var list = daysInWeek
                    .Select(d => new { Day = d, Worked = DayWorked(d) })
                    .OrderBy(d => d.Day)
                    .ToList();

                double sum = list.Sum(x => x.Worked);
                double diff = sum - weekQuota;

               

                var deficits = new Queue<(DateTime day, double need)>(
                    list.Where(x => x.Worked < 8.0 - 1e-6)
                        .Select(x => (x.Day, 8.0 - x.Worked)));

                var excesses = new Queue<(DateTime day, double extra)>(
                    list.Where(x => x.Worked > 8.0 + 1e-6)
                        .Select(x => (x.Day, x.Worked - 8.0)));


                while (deficits.Count > 0 && excesses.Count > 0)
                {
                    var (dDef, need) = deficits.Dequeue();
                    var (dEx, extra) = excesses.Dequeue();
                    var move = Math.Min(need, extra);


                    double cut = TrimAutoFromEnd(dEx, move);
                    if (cut < move - 1e-6)
                        cut += TrimAutoFromStart(dEx, move - cut);

                    if (cut <= 1e-6)
                    {
                        if (extra - cut > 1e-6) excesses.Enqueue((dEx, extra - cut));
                        deficits.Enqueue((dDef, need));
                        continue;
                    }

                    double placed = ExtendDayWithAuto(dDef, cut);
                    if (placed < cut - 1e-6)
                        placed += ExtendDayWithAuto(dDef, cut - placed);


                    double leftNeed = Math.Max(0, need - placed);
                    double leftExtra = Math.Max(0, extra - cut);

                    if (leftNeed > 1e-6) deficits.Enqueue((dDef, leftNeed));
                    if (leftExtra > 1e-6) excesses.Enqueue((dEx, leftExtra));
                }

                foreach (var d in daysInWeek)
                {
                    await new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false))
                        .RegenerateDailyEventsAsync(d);
                }
            }

            workDays = Enumerable.Range(0, (monthEnd - monthStart).Days + 1)
                .Select(i => monthStart.AddDays(i))
                .Where(d => d.DayOfWeek is not DayOfWeek.Saturday and not DayOfWeek.Sunday
                            && !HolidayHelper.IsCzechHoliday(d))
                .ToList();

            double WorkedDay(DateTime d) => new WorkingHoursCalculatorService()
                .DailyMetrics(d, GetEventsForDay(d)).workInclBT;

            var deficitsAll = new Queue<(DateTime day, double need)>(
                workDays.Select(d => (d, WorkedDay(d)))
                        .Where(x => x.Item2 < 8.0 - 1e-6)
                        .Select(x => (x.d, 8.0 - x.Item2)));

            var excessesAll = workDays.Select(d => (day: d, extra: WorkedDay(d) - 8.0))
                                      .Where(x => x.extra > 1e-6)
                                      .ToList();

            while (deficitsAll.Count > 0 && excessesAll.Count > 0)
            {
                var (dDef, need) = deficitsAll.Dequeue();

                int idx = excessesAll.FindIndex(x => WeekStart(x.day) == WeekStart(dDef));
                if (idx < 0) idx = 0; 

                if (excessesAll.Count == 0) break;
                var donor = excessesAll[idx];
                var move = Math.Min(need, donor.extra);


                double cut = TrimAutoFromEnd(donor.day, move);
                if (cut < move - 1e-6)
                    cut += TrimAutoFromStart(donor.day, move - cut);

                if (cut <= 1e-6)
                {
                    excessesAll.RemoveAt(idx);
                    if (need > 1e-6) deficitsAll.Enqueue((dDef, need));
                    continue;
                }

                double placed = ExtendDayWithAuto(dDef, cut);
                if (placed < cut - 1e-6)
                    placed += ExtendDayWithAuto(dDef, cut - placed);

                double leftNeed = Math.Max(0, need - placed);
                donor.extra = Math.Max(0, donor.extra - cut);

                if (donor.extra <= 1e-6) excessesAll.RemoveAt(idx);
                else excessesAll[idx] = donor;

                if (leftNeed > 1e-6) deficitsAll.Enqueue((dDef, leftNeed));
            }

            foreach (var d in workDays)
            {
                await new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false))
                    .RegenerateDailyEventsAsync(d);
            }

            MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
        }


        private void UpdateSingleEventEnd(int eventId, DateTime newEnd)
        {
            using var db = new AppDbContext();
            var ev = db.Events.SingleOrDefault(e => e.Id == eventId && !e.IsDeleted);
            if (ev == null) return;
            if (newEnd < ev.StartTime) newEnd = ev.StartTime;
            ev.EndTime = newEnd;
            db.SaveChanges();
        }

        class DayStat
        {
            public DateTime Date;
            public List<Event> Events;
            public double Worked;
            public double Expected;
            public bool IsFixed;
        }
        private bool IsFullSpecialDay(DayStat stat, GlobalSettings g)
        {
            var only = stat.Events
                          .Where(e => e.EventType != EventType.Work
                                   && e.EventType != EventType.Lunch)
                          .ToList();
            if (only.Count != 1)
                return false;

            var (arr, dep, _, _) = PdfService.GetWeekdayDefaults(g, stat.Date.DayOfWeek);

            var e = only[0];
            return e.StartTime.TimeOfDay <= arr
                && e.EndTime.TimeOfDay >= dep;
        }
        private class BalanceItem
        {
            public DayStat Stat { get; set; }
            public double Amount { get; set; }
        }

        private void BalanceDays(List<DayStat> days)
        {
            var sem = GlobalSettingsService.GetSemesterForDate(DateTime.Today);
            var glob = GlobalSettingsService.LoadGlobalSettings(DateTime.Today.Year, sem)
                       ?? GlobalSettingsService.GetDefaultSettings(DateTime.Today.Year, sem);

            TimeSpan globalStart = TimeSpan.Parse(glob.GlobalStartTime, CultureInfo.InvariantCulture);
            TimeSpan globalEnd = TimeSpan.Parse(glob.GlobalEndTime, CultureInfo.InvariantCulture);

            var (_, _, lunchStartMon, lunchEndMon) = PdfService.GetWeekdayDefaults(glob, DayOfWeek.Monday);

            double baseDayLength = (globalEnd - globalStart).TotalHours;
            double baseLunchLength = (lunchEndMon - lunchStartMon).TotalHours;

            foreach (var stat in days)
            {
                var us = SettingsService.GetUserSettingsForDate(stat.Date);
                TimeSpan arr, dep, ls, le;
                if (us != null)
                {
                    arr = us.ArrivalTime;
                    dep = us.DepartureTime;
                    ls = us.LunchStart;
                    le = us.LunchEnd;
                }
                else
                {
                    (arr, dep, ls, le) = PdfService.GetWeekdayDefaults(glob, stat.Date.DayOfWeek);
                }

                var special = stat.Events
                    .Where(e => e.EventType != EventType.Work && e.EventType != EventType.Lunch)
                    .Select(e => (e.StartTime, e.EndTime));
                var specialMerged = MergeIntervals(special);
                double specialHours = specialMerged.Sum(iv => (iv.end - iv.start).TotalHours);

                stat.Expected = Math.Max(0, baseDayLength - baseLunchLength - specialHours);

                DateTime workWindowStart = stat.Date + arr;
                DateTime workWindowEnd = stat.Date + dep;
                var workIntervals = stat.Events
                    .Where(e => e.EventType == EventType.Work || e.EventType == EventType.BusinessTrip)
                    .Select(e => (
                        Start: e.StartTime < workWindowStart ? workWindowStart : e.StartTime,
                        End: e.EndTime > workWindowEnd ? workWindowEnd : e.EndTime));
                var mergedWork = MergeIntervals(workIntervals);
                stat.Worked = mergedWork.Sum(iv => (iv.end - iv.start).TotalHours);

            }

            var items = days.Where(d => !d.IsFixed)
                              .Select(d => new BalanceItem { Stat = d, Amount = d.Worked - d.Expected })
                              .ToList();
            var deficits = items.Where(x => x.Amount < 0).ToList();
            var excesses = items.Where(x => x.Amount > 0).ToList();
            foreach (var def in deficits)
            {
                double need = -def.Amount;
                foreach (var ex in excesses.Where(x => x.Amount > 0))
                {
                    double take = Math.Min(ex.Amount, need);
                    if (take <= 0) continue;
                    TimeSpan delta = TimeSpan.FromHours(take);

                    var donor = ex.Stat.Events
                        .Where(e => e.EventType == EventType.Work)
                        .OrderByDescending(e => e.EndTime)
                        .FirstOrDefault();
                    if (donor != null)
                    {
                        DateTime minEnd = donor.StartTime;
                        donor.EndTime = Max(donor.EndTime - delta, minEnd);
                    }

                    var gap = FindGap(def.Stat, take, globalStart, globalEnd);
                    var rec = def.Stat.Events
                        .Where(e => e.EventType == EventType.Work)
                        .OrderByDescending(e => e.EndTime)
                        .FirstOrDefault();
                    if (rec == null)
                    {
                        rec = new Event
                        {
                            Title = "Přenos z jiného dne",
                            EventType = EventType.Work,
                            StartTime = gap.start,
                            EndTime = gap.end,
                            IsAutoGenerated = true,
                            AutoGeneratedForDate = def.Stat.Date
                        };
                        CreateEvent(rec);
                        def.Stat.Events.Add(rec);
                        TimeSpan stdLunchLen = lunchEndMon - lunchStartMon;
                        var occupied = def.Stat.Events
                            .Where(e => e.EventType != EventType.Lunch)
                            .Select(e => (e.StartTime, e.EndTime))
                            .OrderBy(iv => iv.StartTime)
                            .ToList();

                        DateTime cursor = def.Stat.Date + globalStart;
                        DateTime windowEnd = def.Stat.Date + globalEnd;
                        (DateTime ls, DateTime le) lunchSlot = (default, default);

                        foreach (var iv in occupied)
                        {
                            if ((iv.StartTime - cursor) >= stdLunchLen)
                            {
                                lunchSlot = (cursor, cursor + stdLunchLen);
                                break;
                            }
                            if (iv.EndTime > cursor)
                                cursor = iv.EndTime;
                        }
                        if (lunchSlot == (default, default)
                            && windowEnd - cursor >= stdLunchLen)
                        {
                            lunchSlot = (cursor, cursor + stdLunchLen);
                        }

                        if (lunchSlot != (default, default))
                        {
                            var evLunch = GetEventsForDay(def.Stat.Date);
                            var lunchExists = evLunch.Where(e => e.EventType == EventType.Lunch
                                       && e.StartTime == e.EndTime).Select(e => (e.Id)).ToList();
                            foreach (var item in lunchExists)
                            {
                                DeleteEvent(item);
                            }
                            var lunch = new Event
                            {
                                Title = "Oběd (auto)",
                                EventType = EventType.Lunch,
                                StartTime = lunchSlot.ls,
                                EndTime = lunchSlot.le,
                                IsAutoGenerated = true,
                                AutoGeneratedForDate = def.Stat.Date
                            };
                            CreateEvent(lunch);
                            def.Stat.Events.Add(lunch);
                        }
                    }
                    else
                    {
                        DateTime maxEnd = def.Stat.Date + globalEnd;
                        var oldEnd = rec.EndTime;
                        rec.EndTime = Min(rec.EndTime + delta, maxEnd);
                    }

                    ex.Amount -= take;
                    need -= take;
                    if (need <= 0) break;
                }
            }
        }
        static DateTime Min(DateTime a, DateTime b) => a < b ? a : b;
        static DateTime Max(DateTime a, DateTime b) => a > b ? a : b;
        private List<(DateTime start, DateTime end)> MergeIntervals(IEnumerable<(DateTime start, DateTime end)> intervals)
        {
            var sorted = intervals.OrderBy(x => x.start).ToList();
            var merged = new List<(DateTime start, DateTime end)>();
            foreach (var seg in sorted)
            {
                if (!merged.Any() || merged.Last().end < seg.start)
                    merged.Add(seg);
                else
                    merged[^1] = (
                        merged.Last().start,
                        merged.Last().end > seg.end ? merged.Last().end : seg.end
                    );
            }
            return merged;
        }

        private (DateTime start, DateTime end) FindGap(DayStat stat, double hours, TimeSpan globalStart, TimeSpan globalEnd)
        {
            var occupied = stat.Events
                .Select(e => (e.StartTime, e.EndTime))
                .OrderBy(iv => iv.StartTime)
                .ToList();

            DateTime cursor = stat.Date + globalStart;
            DateTime windowEnd = stat.Date + globalEnd;

            foreach (var iv in occupied)
            {
                if ((iv.StartTime - cursor).TotalHours >= hours)
                    return (cursor, cursor.AddHours(hours));

                if (iv.EndTime > cursor)
                    cursor = iv.EndTime;
            }

            if ((windowEnd - cursor).TotalHours >= hours)
                return (cursor, cursor.AddHours(hours));

            throw new InvalidOperationException(
                $"Žádné volné místo na {hours:F2}h v {stat.Date:yyyy-MM-dd}");
        }
        private async Task<double> TrimDonorFromEndByUnionAsync(DateTime day, double hoursToCut)
        {
            if (hoursToCut <= 1e-6) return 0;

            var all = GetEventsForDay(day);
            var (arr, dep, _, _) = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false)).GetType()
                .GetMethod("GetWindow", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance) is { } ? (TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero) : (TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero, TimeSpan.Zero);
            var sem = GlobalSettingsService.GetSemesterForDate(day);
            var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                      ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var def = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);
            var us = SettingsService.GetUserSettingsForDate(day);
            var winS = day + (us?.ArrivalTime ?? def.arrival);
            var winE = day + (us?.DepartureTime ?? def.departure);

            var workLike = all.Where(e => (e.EventType == EventType.Work || e.EventType == EventType.BusinessTrip) && !e.IsDeleted);
            var merged = BuildMergedWithOwners(workLike, winS, winE);
            if (merged.Count == 0) return 0;

            double cutLeft = hoursToCut;

            for (int i = merged.Count - 1; i >= 0 && cutLeft > 1e-6; i--)
            {
                var segS = merged[i].s;
                var segE = merged[i].e;
                var owners = merged[i].owners.Distinct().OrderByDescending(ev => ev.EndTime).ToList();

                double segLenH = (segE - segS).TotalHours;
                double take = Math.Min(segLenH, cutLeft);

                DateTime newEndLimit = segE.AddHours(-take);
                foreach (var ev in owners)
                {
                    if (ev.EndTime <= newEndLimit) continue;
                    var newEnd = newEndLimit > ev.StartTime ? newEndLimit : ev.StartTime;
                    if (newEnd < ev.EndTime)
                        UpdateSingleEventEnd(ev.Id, newEnd);
                }

                cutLeft -= take;
            }

            var cutDone = hoursToCut - cutLeft;

            if (cutDone > 1e-6)
            {
                var us2 = SettingsService.GetUserSettingsForDate(day);
                var depT = (us2?.DepartureTime ?? def.departure) - TimeSpan.FromHours(cutDone);
                if (depT < (us2?.ArrivalTime ?? def.arrival)) depT = (us2?.ArrivalTime ?? def.arrival);

                TimeSpan ls = us2?.LunchStart ?? def.lunchStart;
                TimeSpan le = us2?.LunchEnd ?? def.lunchEnd;
                if (le > ls && (le > depT || ls < (us2?.ArrivalTime ?? def.arrival)))
                    (ls, le) = (TimeSpan.Zero, TimeSpan.Zero);

                SettingsService.SaveUserSettingsForDate(day, us2?.ArrivalTime ?? def.arrival, depT, ls, le);
                ReplaceLunchEvent(day, ls, le);

                var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
                await gen.RegenerateDailyEventsAsync(day);
            }

            return cutDone;
        }
        private void DeleteLunchEvents(DateTime day)
        {
            using var db = new AppDbContext();
            var lunches = db.Events
                .Where(e => !e.IsDeleted &&
                            e.StartTime.Date == day.Date &&
                            e.EventType == EventType.Lunch)
                .ToList();
            if (lunches.Count > 0)
            {
                db.Events.RemoveRange(lunches);
                db.SaveChanges();
            }
        }

        private void ReplaceLunchEvent(DateTime day, TimeSpan ls, TimeSpan le)
        {
            DeleteLunchEvents(day);
            if (le > ls)
            {
                using var db = new AppDbContext();
                db.Events.Add(new Event
                {
                    Title = "Oběd (auto)",
                    EventType = EventType.Lunch,
                    StartTime = day + ls,
                    EndTime = day + le,
                    IsAutoGenerated = true,
                    AutoGeneratedForDate = day.Date
                });
                db.SaveChanges();
            }
        }
        public record ImportBatchInfo(string Id, string Label, DateTime RangeStart, DateTime RangeEnd, int EventsCount);

        public IEnumerable<ImportBatchInfo> GetImportBatches()
        {
            using var db = new AppDbContext();

            var rows = db.Events
                .Where(e => !e.IsDeleted && e.ImportBatchId != null)
                .GroupBy(e => new { e.ImportBatchId, e.ImportLabel })
                .Select(g => new
                {
                    Id = g.Key.ImportBatchId!,
                    Label = g.Key.ImportLabel,
                    RangeStart = g.Min(e => e.StartTime),
                    RangeEnd = g.Max(e => e.EndTime),
                    EventsCount = g.Count()
                })
                .OrderByDescending(x => x.RangeStart)
                .AsNoTracking()
                .ToList();

            return rows
                .Select(x => new ImportBatchInfo(
                    x.Id,
                    x.Label ?? "Načtení",
                    x.RangeStart.Date,
                    x.RangeEnd.Date,
                    x.EventsCount))
                .ToList();
        }
        public async Task DeleteEventsByImportIdFastAsync(string batchId)
        {
            using var db = new AppDbContext();

            var affectedDays = await db.Events
                .Where(e => !e.IsDeleted && e.ImportBatchId == batchId)
                .Select(e => e.StartTime.Date)
                .Distinct()
                .ToListAsync();

            #if NET7_0_OR_GREATER
                        await db.Events
                            .Where(e => !e.IsDeleted && e.ImportBatchId == batchId)
                            .ExecuteUpdateAsync(s => s.SetProperty(x => x.IsDeleted, true));
            #else
                var toUpdate = await db.Events
                    .Where(e => !e.IsDeleted && e.ImportBatchId == batchId)
                    .ToListAsync();
                foreach (var ev in toUpdate) ev.IsDeleted = true;
                await db.SaveChangesAsync();
            #endif

            var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
            foreach (var day in affectedDays)
            {
                AdjustUserSettingsAfterDeletion(day);
                await gen.RegenerateDailyEventsAsync(day);
            }

            MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
        }
        public async Task BulkSoftDeleteImportedInRangeAsync(DateTime from, DateTime to)
        {
            var s = from.Date;
            var e = to.Date;

            using var db = new AppDbContext();

            var affectedDays = await db.Events
                .Where(x => !x.IsDeleted
                            && x.ImportBatchId != null
                            && x.StartTime.Date >= s
                            && x.StartTime.Date <= e)
                .Select(x => x.StartTime.Date)
                .Distinct()
                .ToListAsync();

            #if NET7_0_OR_GREATER
                        await db.Events
                            .Where(x => !x.IsDeleted
                                        && x.ImportBatchId != null
                                        && x.StartTime.Date >= s
                                        && x.StartTime.Date <= e)
                            .ExecuteUpdateAsync(u => u.SetProperty(x => x.IsDeleted, true));
            #else
                var list = await db.Events
                    .Where(x => !x.IsDeleted
                                && x.ImportBatchId != null
                                && x.StartTime.Date >= s
                                && x.StartTime.Date <= e)
                    .ToListAsync();
                foreach (var ev in list) ev.IsDeleted = true;
                await db.SaveChangesAsync();
            #endif

            var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
            foreach (var day in affectedDays)
            {
                AdjustUserSettingsAfterDeletion(day);
                await gen.RegenerateDailyEventsAsync(day);
            }

            MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
        }
        public void DeleteEventsByImportId(string batchId)
        {
            var toDelete = GetAllEvents()
                .Where(e => e.ImportBatchId == batchId)
                .ToList();

            foreach (var ev in toDelete)
                DeleteEvent(ev.Id);
        }
        public void DeleteEventCascadeAndCleanup(int id)
        {
            using var db = new AppDbContext();

            var toDelete = db.Events
                .Where(e => e.Id == id || e.ParentEventId == id)
                .ToList();

            if (toDelete.Count == 0) return;

            var affectedDates = toDelete
                .Select(e => e.StartTime.Date)
                .Distinct()
                .ToList();

            foreach (var e in toDelete)
                e.IsDeleted = true;

            db.SaveChanges();

            foreach (var day in affectedDates)
            {
                bool anyLeft = db.Events.Any(e => !e.IsDeleted && e.StartTime.Date == day);
                if (!anyLeft)
                {
                    SettingsService.DeleteUserSettingsForDate(day);
                    continue;
                }

                AdjustUserSettingsAfterDeletion(day);

                var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(false));
                gen.RegenerateDailyEventsAsync(day).GetAwaiter().GetResult();

                MessageBus.Current.SendMessage(new AutoEventsGeneratedMessage());
                MessageBus.Current.SendMessage(new UserSettingsChangedMessage(day));
            }
        }
        private void AdjustUserSettingsAfterDeletion(DateTime day)
        {
            var events = GetEventsForDay(day)
                .Where(e => e.EventType != EventType.Lunch)
                .OrderBy(e => e.StartTime)
                .ToList();

            if (events.Count == 0)
            {
                SettingsService.DeleteUserSettingsForDate(day);
                return;
            }

            var firstStart = events.First().StartTime;
            var lastEnd = events.Last().EndTime;

            var sem = GlobalSettingsService.GetSemesterForDate(day);
            var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                     ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
            var def = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);
            var us = SettingsService.GetUserSettingsForDate(day);

            var arr = firstStart.TimeOfDay;
            var dep = lastEnd.TimeOfDay;

            TimeSpan ls = TimeSpan.Zero, le = TimeSpan.Zero;
            if (us != null && us.LunchEnd > us.LunchStart)
            {
                if (us.LunchStart >= arr && us.LunchEnd <= dep)
                {
                    ls = us.LunchStart; le = us.LunchEnd;
                }
            }
            else if (def.lunchEnd > def.lunchStart && def.lunchStart >= arr && def.lunchEnd <= dep)
            {
                ls = def.lunchStart; le = def.lunchEnd;
            }

            SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
        }

        public async Task TrimOvertimeByAutoBlocksAsync(DateTime day)
        {
            var calc = new WorkingHoursCalculatorService();
            var all = GetEventsForDay(day);
            var m = calc.DailyMetrics(day, all);
            var over = Math.Max(0, (m.specialNonPc + m.workInclBT) - 8.0);
            if (over <= 1e-6) return;

            var lastAuto = all
                .Where(e => e.IsAutoGenerated && e.EventType == EventType.Work && !e.IsDeleted)
                .OrderByDescending(e => e.EndTime)
                .FirstOrDefault();

            if (lastAuto != null)
            {
                var cut = Math.Min(over, (lastAuto.EndTime - lastAuto.StartTime).TotalHours);
                if (cut > 1e-6)
                {
                    var newEnd = lastAuto.EndTime - TimeSpan.FromHours(cut);
                    if (newEnd < lastAuto.StartTime) newEnd = lastAuto.StartTime;

                    UpdateSingleEventEnd(lastAuto.Id, newEnd);

                    var us = SettingsService.GetUserSettingsForDate(day);
                    var sem = GlobalSettingsService.GetSemesterForDate(day);
                    var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                             ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
                    var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);

                    var arr = us?.ArrivalTime ?? defArr;
                    var dep = us?.DepartureTime ?? defDep;
                    var ls = us?.LunchStart ?? defLs;
                    var le = us?.LunchEnd ?? defLe;

                    dep = newEnd.TimeOfDay > arr ? newEnd.TimeOfDay : arr;

                    if (le > ls && (le > dep || ls < arr))
                    {
                        var len = le - ls;
                        var nls = dep - len;
                        if (nls >= arr)
                            (ls, le) = (nls, dep);
                        else
                            (ls, le) = (TimeSpan.Zero, TimeSpan.Zero);
                    }

                    SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
                    ReplaceLunchEvent(day, ls, le);
                    var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(true));
                    await gen.RegenerateDailyEventsAsync(day);
                    return;
                }
            }

            var firstAuto = all
                .Where(e => e.IsAutoGenerated && e.EventType == EventType.Work && !e.IsDeleted)
                .OrderBy(e => e.StartTime)
                .FirstOrDefault();

            if (firstAuto != null)
            {
                var cut = Math.Min(over, (firstAuto.EndTime - firstAuto.StartTime).TotalHours);
                if (cut > 1e-6)
                {
                    var newStart = firstAuto.StartTime + TimeSpan.FromHours(cut);
                    if (newStart > firstAuto.EndTime) newStart = firstAuto.EndTime;

                    using (var db = new AppDbContext())
                    {
                        var ev = db.Events.Single(x => x.Id == firstAuto.Id);
                        ev.StartTime = newStart;
                        db.SaveChanges();
                    }

                    var us = SettingsService.GetUserSettingsForDate(day);
                    var sem = GlobalSettingsService.GetSemesterForDate(day);
                    var gl = GlobalSettingsService.LoadGlobalSettings(day.Year, sem)
                             ?? GlobalSettingsService.GetDefaultSettings(day.Year, sem);
                    var (defArr, defDep, defLs, defLe) = PdfService.GetWeekdayDefaults(gl, day.DayOfWeek);

                    var arr = us?.ArrivalTime ?? defArr;
                    var dep = us?.DepartureTime ?? defDep;
                    var ls = us?.LunchStart ?? defLs;
                    var le = us?.LunchEnd ?? defLe;

                    arr = newStart.TimeOfDay < dep ? newStart.TimeOfDay : dep;

                    if (le > ls && (le > dep || ls < arr))
                    {
                        var len = le - ls;
                        var nle = arr + len;
                        if (nle <= dep)
                            (ls, le) = (arr, nle);
                        else
                            (ls, le) = (TimeSpan.Zero, TimeSpan.Zero);
                    }

                    SettingsService.SaveUserSettingsForDate(day, arr, dep, ls, le);
                    ReplaceLunchEvent(day, ls, le);
                    var gen = new AutomaticEventsGeneratorService(this, _ => Task.FromResult(true));
                    await gen.RegenerateDailyEventsAsync(day);
                }
            }
        }
    }
}
