using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Shapes;
using Avalonia.Layout;
using Avalonia.Media;
using System.Collections.Generic;
using TeacherScheduleApp.Models;

namespace TeacherScheduleApp.Controls
{
    public class CalendarEventControl : ContentControl
    {

        public int DayIndex { get; set; }
        public double StartHour { get; set; }
        public double EndHour { get; set; }
        public int OverlapIndex { get; set; }  
        public int OverlapCount { get; set; }

        public CalendarEventControl(Event ev)
        {
            HorizontalContentAlignment = HorizontalAlignment.Stretch;
            IBrush brush;
            if (ev.EventType == EventType.Lunch)
            {
                brush = ev.HasCollision ? Brushes.Red : Brushes.Orange;
            }
            else if (ev.EventType == EventType.Work)
            {
                brush = (!ev.IsAutoGenerated && ev.HasCollision) ? Brushes.Red : Brushes.SteelBlue;
            }
            else if (IsSpecial(ev.EventType))
            {
                brush = SpecialBrush(ev.EventType);
            }
            else
            {
                brush = Brushes.Gray;
            }

            var border = new Border
            {
                Background = Brushes.White,
                BorderBrush = brush,
                BorderThickness = new Thickness(1),
                CornerRadius = new CornerRadius(4),
                Padding = new Thickness(4),
                Margin = new Thickness(2, 2, 2, 0),
                HorizontalAlignment = HorizontalAlignment.Stretch
            };

            var grid = new Grid
            {
                ColumnDefinitions = new ColumnDefinitions("Auto,*"),
                RowDefinitions = new RowDefinitions("Auto")
            };

            var bullet = new Ellipse
            {
                Width = 8,
                Height = 8,
                Fill = brush,
                VerticalAlignment = VerticalAlignment.Center,
                Margin = new Thickness(0, 0, 6, 0)
            };
            Grid.SetColumn(bullet, 0);
            grid.Children.Add(bullet);

            var textPanel = new StackPanel
            {
                Orientation = Orientation.Vertical,
                Spacing = 2
            };
            Grid.SetColumn(textPanel, 1);

            var titleBlock = new TextBlock
            {
                Text = ev.Title,
                FontWeight = FontWeight.Bold,
                Foreground = Brushes.Black,
                TextWrapping = TextWrapping.Wrap,
                TextTrimming = TextTrimming.CharacterEllipsis,
                MaxLines = 2,
            };
            textPanel.Children.Add(titleBlock);

            if (!string.IsNullOrWhiteSpace(ev.Description))
            {
                var descBlock = new TextBlock
                {
                    Text = ev.Description,
                    Foreground = Brushes.Gray,
                    TextWrapping = TextWrapping.Wrap,
                    TextTrimming = TextTrimming.WordEllipsis,
                    MaxLines = 3,
                    FontSize = 12
                };
                textPanel.Children.Add(descBlock);

                ToolTip.SetTip(textPanel, $"{ev.Title}\n\n{ev.Description}");
            }
            else
            {
                ToolTip.SetTip(textPanel, ev.Title);
            }
            if (ev.IsInactive && !IsSpecial(ev.EventType))
            {
                border.Opacity = 0.45;
                IsHitTestVisible = false;
            }
            grid.Children.Add(textPanel);
            border.Child = grid;
            Content = border;          
        }
        private static readonly HashSet<EventType> SpecialTypes = new()
        {
            EventType.DayOff, EventType.Illness, EventType.Vacation,
            EventType.Ocr, EventType.Doctor, EventType.BusinessTrip, EventType.Holiday
        };
        private static bool IsSpecial(EventType t) => SpecialTypes.Contains(t);

        private static IBrush SpecialBrush(EventType t) => t switch
        {
            EventType.Vacation => Brushes.MediumSeaGreen,
            EventType.Illness => Brushes.MediumOrchid,
            EventType.DayOff => Brushes.SlateGray,
            EventType.Ocr => Brushes.DarkOrange,
            EventType.Doctor => Brushes.SeaGreen,
            EventType.BusinessTrip => Brushes.SteelBlue,
            EventType.Holiday => Brushes.Goldenrod,
            _ => Brushes.Gray
        };
    }
}
