using System;
using System.Globalization;
using System.Linq;
using TeacherScheduleApp.Models;
using TeacherScheduleApp.Services;

namespace TeacherScheduleApp.Helpers
{
    public static class BalanceFingerprint
    {
        private static ulong Fnva64(ulong h, ulong x) => (h ^ x) * 1099511628211UL;

        private static ulong HashOne(Event e)
        {
            unchecked
            {
                ulong h = 1469598103934665603UL;
                h = Fnva64(h, (ulong)e.Id);
                h = Fnva64(h, (ulong)e.EmployeeId);
                h = Fnva64(h, (ulong)e.StartTime.Ticks);
                h = Fnva64(h, (ulong)e.EndTime.Ticks);
                h = Fnva64(h, (ulong)e.EventType);
                h = Fnva64(h, e.IsDeleted ? 1UL : 0UL);
                h = Fnva64(h, e.IsAutoGenerated ? 1UL : 0UL);
                h = Fnva64(h, e.AllDay ? 1UL : 0UL);
                h = Fnva64(h, (ulong)(e.ParentEventId ?? 0));
                return h;
            }
        }

        public static string ForMonth(EventService svc, int employeeId, int year, int month)
        {
            var date = new DateTime(year, month, 1);

            var list = svc.GetEventsForMonth(employeeId, date)
              .Where(e => !e.IsDeleted)
              .OrderBy(e => e.StartTime)
              .ThenBy(e => e.Id)
              .ToList();

            unchecked
            {
                ulong h = 1469598103934665603UL;
                h = Fnva64(h, (ulong)employeeId);
                h = Fnva64(h, (ulong)year);
                h = Fnva64(h, (ulong)month);
                h = Fnva64(h, (ulong)list.Count);

                foreach (var e in list)
                    h = Fnva64(h, HashManual(e));

                return $"{employeeId}:{year:D4}-{month:D2}:{h:X16}";
            }
        }

        public static string ForWeek(EventService svc, int employeeId, DateTime anyDate)
        {
            int isoYear = ISOWeek.GetYear(anyDate);
            int isoWeek = ISOWeek.GetWeekOfYear(anyDate);

            var monday = anyDate.Date.AddDays(-(((int)anyDate.DayOfWeek - (int)DayOfWeek.Monday + 7) % 7));
            var sunday = monday.AddDays(6);

            var list = svc.GetEventsForRange(employeeId, monday, sunday.AddDays(1))
                .Where(e => !e.IsDeleted)
                .Where(e => !e.IsAutoGenerated)
                .OrderBy(e => e.StartTime)
                .ThenBy(e => e.Id)
                .ToList();

            unchecked
            {
                ulong h = 1469598103934665603UL;
                h = Fnva64(h, (ulong)employeeId);
                h = Fnva64(h, (ulong)isoYear);
                h = Fnva64(h, (ulong)isoWeek);
                h = Fnva64(h, (ulong)list.Count);

                foreach (var e in list)
                    h = Fnva64(h, HashOne(e));

                return $"{employeeId}:{isoYear}-W{isoWeek:D2}:{h:X16}";
            }
        }

        private static ulong HashManual(Event e)
        {
            unchecked
            {
                ulong h = 1469598103934665603UL;
                h = Fnva64(h, (ulong)e.Id);
                h = Fnva64(h, (ulong)e.EmployeeId);
                h = Fnva64(h, (ulong)e.StartTime.Ticks);
                h = Fnva64(h, (ulong)e.EndTime.Ticks);
                h = Fnva64(h, (ulong)e.EventType);
                h = Fnva64(h, e.IsDeleted ? 1UL : 0UL);
                h = Fnva64(h, e.AllDay ? 1UL : 0UL);
                h = Fnva64(h, (ulong)(e.ParentEventId ?? 0));
                h = Fnva64(h, e.ImportBatchId != null ? 1UL : 0UL);
                return h;
            }
        }

        public static string ForMonth(EventService svc, int year, int month)
            => ForMonth(svc, EventService.DefaultEmployeeId, year, month);
    }
}