using System;
using System.Linq;
using TeacherScheduleApp.Models;
using TeacherScheduleApp.Services;

namespace TeacherScheduleApp.Helpers
{
    public static class BalanceFingerprint
    {
        private static ulong Fnva64(ulong h, ulong x) => (h ^ x) * 1099511628211UL;

        private static ulong HashOne(Event e)
        {
            unchecked
            {
                ulong h = 1469598103934665603UL;
                h = Fnva64(h, (ulong)e.Id);
                h = Fnva64(h, (ulong)e.StartTime.Ticks);
                h = Fnva64(h, (ulong)e.EndTime.Ticks);
                h = Fnva64(h, (ulong)e.EventType);
                h = Fnva64(h, e.IsDeleted ? 1UL : 0UL);
                h = Fnva64(h, e.IsAutoGenerated ? 1UL : 0UL);
                h = Fnva64(h, e.AllDay ? 1UL : 0UL);
                h = Fnva64(h, (ulong)(e.ParentEventId ?? 0));
                return h;
            }
        }

        public static string ForMonth(EventService svc, int year, int month)
        {
            var list = svc.GetEventsForMonth(new DateTime(year, month, 1));
            unchecked
            {
                ulong h = 1469598103934665603UL;
                h = Fnva64(h, (ulong)list.Count);
                foreach (var e in list.OrderBy(x => x.StartTime).ThenBy(x => x.Id))
                    h = Fnva64(h, HashOne(e));

                ulong movedSum = 0UL;
                var movedIn = WorkTransferReportingService.GetMovedInDetails(new DateTime(year, month, 1));
                foreach (var (d, hrs) in movedIn)
                {
                    if (d.Year == year && d.Month == month)
                        movedSum += (ulong)(hrs * 1000);
                }
                h = Fnva64(h, movedSum);

                return $"{year:D4}-{month:D2}:{h:X16}";
            }
        }
    }
}
